/**
 * Auto-generated articles bundle
 * Generated at: 2026-03-29T20:41:12.958Z
 *
 * This file contains all markdown articles bundled into the JavaScript.
 * DO NOT edit this file manually - it will be regenerated on build.
 *
 * To modify articles, edit the .md files in the /docs folder.
 */

import type { Article } from '../services/article.service';

export const ARTICLES_BUNDLE: Article[] = [
  {
    id: '01-welcome',
    title: 'Welcome',
    content: `# Welcome to My Blog

Hello! I'm so glad you're here. This is the beginning of what I hope will be a meaningful journey together.

## Table of Contents

- [Why I Started This Blog](#why-i-started-this-blog)
- [What You'll Find Here](#what-youll-find-here)
- [My Story](#my-story)
- [Let's Connect](#lets-connect)

## Why I Started This Blog

For years, I've been collecting stories, experiences, and lessons in journals, photo albums, and scattered notes across my devices. But I realized that the true joy of sharing comes when we open our hearts to a wider community.

This blog is my digital home—a place where I can:

- **Share authentically** about my journey, struggles, and triumphs
- **Connect with like-minded souls** who appreciate genuine storytelling
- **Document the moments** that make life beautiful
- **Inspire others** to live intentionally and creatively

> "The best things in life aren't things." — Unknown

## What You'll Find Here

This blog is organized into several categories, each representing a different aspect of my life and interests:

### 📖 Personal Stories
Reflections on life, growth, and the lessons I'm learning along the way. These are the posts closest to my heart.

### 🌍 Travel Adventures
Stories from my journeys—both near and far. You'll find destination guides, travel tips, and the beautiful moments captured through my lens.

### 🎨 Creative Projects
A showcase of my creative endeavors, from photography to DIY projects. I believe everyone has a creative spark, and I love exploring mine.

### 🏡 Lifestyle & Wellness
Tips, routines, and thoughts on living a balanced, intentional life. Because how we live each day matters.

### 🌱 Growth & Learning
Books I've read, courses I've taken, and insights I've gained. Personal development is a lifelong journey.

## My Story

I'm a creative soul based on this beautiful planet, with a heart full of dreams and a mind full of stories. 

### What Drives Me

- **Curiosity** about the world and the people in it
- **Passion** for visual storytelling and authentic expression
- **Belief** that everyone has a unique story worth telling
- **Love** for connecting with others through shared experiences

### My Journey

Like many of us, my path hasn't been linear. I've explored different interests, tried various careers, and learned that the detours often lead to the most beautiful destinations.

What started as a hobby—taking photos, writing thoughts, creating things—has evolved into this space where I can share my perspective with the world.

### What I Value

| Value | What It Means to Me |
|-------|---------------------|
| **Authenticity** | Being real, vulnerable, and true to myself |
| **Creativity** | Finding beauty and making things that matter |
| **Connection** | Building genuine relationships with readers |
| **Growth** | Always learning, evolving, and becoming |
| **Gratitude** | Appreciating every moment and opportunity |

## Behind the Scenes

This blog is more than just words and images—it's a labor of love. Here's a glimpse of what goes into each post:

\`\`\`mermaid
flowchart LR
    A[Inspiration] --> B[Planning]
    B --> C[Creating]
    C --> D[Photography]
    C --> E[Writing]
    D --> F[Editing]
    E --> F
    F --> G[Publishing]
    G --> H[Sharing]
    H --> I[Connecting with You]
\`\`\`

### My Creative Process

1. **Finding Inspiration** - Often happens during morning walks or quiet moments
2. **Capturing Moments** - Camera in hand, always ready for the perfect shot
3. **Writing from the Heart** - No filters, just honest words
4. **Polishing with Care** - Because quality matters
5. **Sharing with Hope** - That my words might touch someone's day

## Let's Connect

I'd love to hear from you! This blog isn't a monologue—it's a conversation.

### Ways to Reach Out

- **Email**: hello@example.com
- **Instagram**: Share your thoughts on my latest posts
- **Facebook**: Join our growing community
- **Twitter**: Quick conversations and updates

### What I'd Love to Hear

- Your own stories and experiences
- Topics you'd like me to write about
- Feedback on posts that resonated with you
- Collaboration ideas and creative projects

## A Note on Comments

Every comment, message, and share means the world to me. I try to respond to each one personally, because I believe in the power of genuine connection.

If you've read this far, thank you. You're already part of this journey, and I can't wait to see where it takes us together.

---

**With love and gratitude,**  
*Naranyala*

💌 *P.S. Don't forget to subscribe or follow on social media to stay updated on new posts!*
`
  },
  {
    id: '02-cape-town-adventure',
    title: 'Cape town adventure',
    content: `# My Cape Town Adventure

The Mother City has a way of capturing your heart and never quite letting go. This is the story of my recent weekend escape to one of Earth's most beloved destinations.

## Table of Contents

- [The Call of the City](#the-call-of-the-city)
- [Day 1: Table Mountain & Bo-Kaap](#day-1-table-mountain--bo-kaap)
- [Day 2: V&A Waterfront & Robben Island](#day-2-va-waterfront--robben-island)
- [Day 3: Cape Point & Penguins](#day-3-cape-point--penguins)
- [Travel Tips](#travel-tips)
- [Photo Gallery](#photo-gallery)

## The Call of the City

Sometimes you just need to pack a bag and go. After weeks of non-stop work and the general hustle of daily life, I felt that familiar pull—the mountain calling my name, the ocean whispering secrets, and the city's vibrant energy waiting to be experienced.

> "Cape Town is not just a place; it's a feeling." — Unknown

### Planning the Trip

I'm a firm believer that the best adventures happen with a mix of planning and spontaneity. Here's what I had on my itinerary:

| Day | Main Activity | Backup Plan |
|-----|---------------|-------------|
| 1 | Table Mountain hike | Cable car if weather bad |
| 2 | Robben Island tour | V&A Waterfront exploration |
| 3 | Cape Point drive | Boulders Beach penguins |

## Day 1: Table Mountain & Bo-Kaap

### Morning: Conquering the Mountain

There's something profoundly humbling about standing atop Table Mountain, looking out over a city nestled between mountain and sea. I chose to hike up via Platteklip Gorge—the most direct route, though not for the faint of heart.

**The Hike Stats:**
- **Distance**: 3km (one way)
- **Duration**: 2-3 hours up
- **Elevation gain**: ~600 meters
- **Difficulty**: Moderate to challenging

\`\`\`mermaid
flowchart TD
    A[Start at Tafelberg Road] --> B[Platteklip Gorge Trail]
    B --> C[First Water Point]
    C --> D[Disa Gorge Junction]
    D --> E[Final Climb]
    E --> F[Table Mountain Summit]
    F --> G[Cable Car Down]
    G --> H[Celebration Coffee]
\`\`\`

### The View from the Top

Words can't quite capture it, but I'll try:

The city sprawled below like a miniature model. The Atlantic Ocean shimmering in the distance. The iconic stadium looking like a white basket. And the famous "tablecloth" of clouds slowly rolling over the edge.

I sat there for what felt like hours, just breathing. This is why I travel. This is why I seek out these moments of awe.

### Afternoon: Bo-Kaap's Colorful Streets

After descending (I took the cable car down—my knees thanked me), I headed to Bo-Kaap, the historic Malay Quarter famous for its brightly colored houses and cobblestone streets.

**What I Loved:**
- 📸 Every corner is Instagram-worthy
- 🕌 The Bo-Kaap Museum tells powerful stories
- 🍛 Amazing Cape Malay cuisine
- 🎨 Rich cultural heritage

### Evening: Sunset at Signal Hill

No Cape Town trip is complete without watching the sunset from Signal Hill. I packed a picnic, found a spot away from the crowds, and watched as the sky transformed into a canvas of orange, pink, and purple.

## Day 2: V&A Waterfront & Robben Island

### Morning: A Journey to Robben Island

The ferry ride to Robben Island was calm, the morning sun reflecting off the water. But the destination holds heavy history—this is where Nelson Mandela spent 18 of his 27 years in prison.

**The Tour Experience:**
- ⏱️ Duration: 3.5 hours total
- 🚌 Bus tour led by former political prisoners
- 🏠 Visit to Mandela's cell
- 📚 Deeply moving and educational

> "Education is the most powerful weapon which you can use to change the world." — Nelson Mandela

Walking through the prison cells, hearing stories from someone who lived through it, was profoundly emotional. It's a reminder of the price of freedom and the power of forgiveness.

### Afternoon: V&A Waterfront Exploration

Back on the mainland, I wandered through the V&A Waterfront—a blend of historic harbor and modern entertainment.

**Highlights:**
- Shopping at the Watershed (local crafts!)
- Street performers and live music
- The Cape Wheel for panoramic views
- Countless dining options

### Evening: Dinner with a View

I treated myself to dinner at a waterfront restaurant, watching the boats bob in the harbor as I savored fresh seafood. Sometimes solitude is exactly what you need.

## Day 3: Cape Point & Penguins

### Morning: The Edge of Africa

Cape Point, where the Atlantic and Indian Oceans meet, is dramatic in that way that makes you feel wonderfully small. The cliffs, the crashing waves, the endless horizon—it's nature at its most magnificent.

**Getting There:**
- 🚗 2-hour drive from Cape Town
- 🅿️ Parking available at the reserve
- 🚡 Funicular optional (I walked—more fun!)

### The Lighthouse

I hiked up to the old lighthouse for the ultimate view. The path is steep but short, and the panorama is absolutely worth it.

\`\`\`mermaid
flowchart LR
    A[Parking Area] --> B[Visitor Center]
    B --> C[Hiking Trail]
    C --> D[Lighthouse]
    D --> E[Cape Point Peak]
    E --> F[Return Journey]
\`\`\`

### Afternoon: Penguins at Boulders Beach

No visit to the Cape Peninsula is complete without meeting the penguins! Boulders Beach is home to a colony of African penguins, and watching these tuxedoed characters waddle, swim, and squawk was the perfect end to my trip.

**Penguin Facts:**
- 🐧 African penguins are endangered
- 🏠 They nest in burrows or under rocks
- 🐟 They can dive up to 30 meters deep
- 💑 They mate for life

## Travel Tips

### Getting Around

| Option | Pros | Cons |
|--------|------|------|
| Rental car | Flexibility, convenience | Parking can be tricky |
| Uber/Bolt | No parking worries | Can add up cost-wise |
| MyCiTi bus | Affordable, scenic | Limited routes |
| Tour groups | Hassle-free | Less flexibility |

### Where to Stay

**Budget-Friendly:**
- Long Street backpackers
- Observatory hostels

**Mid-Range:**
- Gardens boutique hotels
- Sea Point guesthouses

**Luxury:**
- V&A Waterfront hotels
- Camps Bay resorts

### What to Pack

- ☀️ Sunscreen (the African sun is no joke)
- 🧥 Layers (weather changes quickly)
- 👟 Comfortable walking shoes
- 📷 Camera with extra batteries
- 💧 Reusable water bottle

### Safety Tips

Cape Town is generally safe for tourists, but like any major city, it's wise to:
- Stay aware of your surroundings
- Don't flash valuables
- Use reputable transport
- Avoid isolated areas at night
- Keep emergency numbers handy

## Photo Gallery

While I can't embed all my photos here, here are some of my favorite shots from the trip:

1. **Sunrise from Table Mountain** - The city waking up below
2. **Bo-Kaap Colors** - A rainbow of houses
3. **Robben Island Ferry** - Journey into history
4. **Cape Point Lighthouse** - Standing at the edge
5. **Penguin Parade** - Boulders Beach residents
6. **Signal Hill Sunset** - Nature's masterpiece

---

## Final Thoughts

Cape Town is one of those places that stays with you long after you've left. It's in the way the light hits the mountain at golden hour, the warmth of the people, the rich tapestry of cultures, and the constant reminder of both struggle and triumph.

I left feeling refreshed, inspired, and deeply grateful for the beauty that exists in our world. If you've never been, I can't recommend it enough. And if you have, you know exactly what I'm talking about.

**Until next time, Cape Town.** 🌊

---

*Have you been to Cape Town? I'd love to hear your favorite spots in the comments!*
`
  },
  {
    id: '03-finding-balance-wellness',
    title: 'Finding balance wellness',
    content: `# Finding Balance: My Wellness Journey

In a world that glorifies busy, choosing balance is a radical act of self-love. This is my story of learning to slow down, breathe deeper, and live more intentionally.

## Table of Contents

- [The Wake-Up Call](#the-wake-up-call)
- [What Wellness Means to Me](#what-wellness-means-to-me)
- [My Daily Rituals](#my-daily-rituals)
- [Lessons Learned](#lessons-learned)
- [Tips for Your Journey](#tips-for-your-journey)

## The Wake-Up Call

It happened on an ordinary Tuesday. I was rushing from one commitment to another, running on caffeine and determination, when my body essentially said: *Enough.*

I woke up exhausted despite eight hours of sleep. My mind was foggy. My creativity—the thing I've always relied on—felt distant. I was doing all the things, checking all the boxes, but I wasn't *living*—I was surviving.

> "Rest is not idle, is not wasteful. Sometimes rest is the most productive thing you can do." — Unknown

### Signs I Was Out of Balance

Looking back, the warning signs were there:

| Symptom | What I Ignored |
|---------|----------------|
| Constant fatigue | "I'll sleep when I'm done" |
| Creative block | "I just need to push through" |
| Irritability | "It's just stress" |
| Poor sleep | "I'll relax later" |
| Skipping meals | "I'm too busy" |

Sound familiar? You're not alone.

## What Wellness Means to Me

Wellness isn't about perfect green smoothies, expensive yoga retreats, or having a pristine home (though those things can be nice). 

**True wellness is:**
- 🧠 **Mental clarity** - Knowing what matters and letting go of the rest
- 💪 **Physical vitality** - Moving your body in ways that feel good
- 💝 **Emotional balance** - Allowing all feelings without being consumed by them
- 🌱 **Spiritual connection** - Feeling part of something bigger
- 🤝 **Social nourishment** - Relationships that energize rather than drain

### The Wellness Wheel

\`\`\`mermaid
flowchart TB
    subgraph Wellness["My Wellness Wheel"]
        direction TB
        Physical[Physical Health<br/>Movement, Nutrition, Sleep]
        Mental[Mental Health<br/>Mindfulness, Learning]
        Emotional[Emotional Health<br/>Self-compassion, Expression]
        Social[Social Health<br/>Relationships, Boundaries]
        Creative[Creative Health<br/>Expression, Play]
        Spiritual[Spiritual Health<br/>Purpose, Connection]
    end
    
    Physical --> Mental
    Mental --> Emotional
    Emotional --> Social
    Social --> Creative
    Creative --> Spiritual
    Spiritual --> Physical
\`\`\`

Wellness is holistic. When one area suffers, others feel it. When one thrives, others benefit.

## My Daily Rituals

I'm a firm believer that small, consistent actions create big changes. Here are the rituals that transformed my life:

### Morning Routine (The Foundation)

**5:30 AM - Wake Up**
- No phone for the first hour (game-changer!)
- Glass of water with lemon
- 5 minutes of gratitude journaling

**6:00 AM - Movement**
- 20 minutes of yoga or stretching
- Sometimes a walk around the neighborhood
- Always listening to my body

**6:30 AM - Mindfulness**
- 10 minutes of meditation
- Setting intentions for the day
- Breathing exercises

**7:00 AM - Nourishment**
- Nutritious breakfast (usually something with protein)
- Herbal tea or coffee, enjoyed slowly
- Reading or quiet time

### Evening Routine (The Unwind)

**8:00 PM - Digital Sunset**
- Screens off or on night mode
- Dimming the lights
- Calming music or silence

**9:00 PM - Reflection**
- Journaling about the day
- Three things I'm grateful for
- Releasing what didn't serve me

**9:30 PM - Preparation**
- Skincare routine (self-care, not chore)
- Preparing for tomorrow
- Reading a few pages

**10:00 PM - Sleep**
- Cool, dark room
- No caffeine after 2 PM
- Consistent bedtime

## Lessons Learned

### 1. Balance Isn't Perfect

I used to think balance meant equal time for everything. Now I know it's about **flexibility**—some days work needs more, some days rest does.

> "Balance is not something you find, it's something you create." — Jana Kingsford

### 2. Rest Is Productive

This was hard to learn. But rest isn't laziness—it's essential for:
- Creative problem-solving
- Emotional regulation
- Physical recovery
- Mental clarity

### 3. Boundaries Are Love

Saying no to others often means saying yes to yourself. Boundaries aren't walls; they're gates with you as the gatekeeper.

**My Boundary Framework:**

\`\`\`mermaid
flowchart LR
    A[Request Comes In] --> B{Does This Align?}
    B -->|Yes| C[Consider Carefully]
    B -->|No| D[Polite Decline]
    C --> E{Do I Have Capacity?}
    E -->|Yes| F[Enthusiastic Yes]
    E -->|No| D
    D --> G[No Guilt]
    F --> G
\`\`\`

### 4. Comparison Is the Thief of Joy

Social media makes it easy to compare my behind-the-scenes to everyone else's highlight reel. I've learned to:
- Limit social media time
- Follow accounts that inspire, not diminish
- Remember: everyone struggles

### 5. Small Steps Create Big Changes

You don't need a complete life overhaul. Start small:
- One extra glass of water
- Five minutes of stretching
- One deep breath before reacting

## Tips for Your Journey

### Start Here

| If You're Struggling With... | Try This First |
|------------------------------|----------------|
| Exhaustion | Prioritize sleep for one week |
| Stress | 5 minutes of deep breathing daily |
| Overwhelm | Write down top 3 priorities daily |
| Disconnection | Reach out to one friend this week |
| Creative block | Consume inspiring content daily |

### My Favorite Wellness Tools

**Apps I Love:**
- 📱 Headspace - Guided meditation
- 📱 Daylio - Mood tracking
- 📱 Forest - Focus and phone detox
- 📱 Insight Timer - Free meditation library

**Books That Changed Me:**
- "Atomic Habits" by James Clear
- "The Power of Now" by Eckhart Tolle
- "Breath" by James Nestor
- "Why We Sleep" by Matthew Walker

**Simple Practices:**
- Morning pages (stream of consciousness writing)
- Weekly nature walks
- Digital sabbaths (one day screen-free)
- Gratitude jar
- Monthly self-care Sundays

### Creating Your Own Routine

Don't copy mine exactly—create what works for YOU:

1. **Assess your current state** - Where are you now?
2. **Identify your needs** - What's missing?
3. **Start small** - One or two changes at a time
4. **Be consistent** - Daily practice beats perfection
5. **Adjust as needed** - Listen to your body

\`\`\`mermaid
flowchart TD
    A[Self-Assessment] --> B[Identify Needs]
    B --> C[Choose 1-2 Practices]
    C --> D[Commit for 21 Days]
    D --> E{How Do You Feel?}
    E -->|Better| F[Continue & Add More]
    E -->|Same| G[Adjust Approach]
    E -->|Worse| H[Try Something Else]
    F --> I[Maintain & Evolve]
    G --> D
    H --> D
\`\`\`

## The Reality Check

Let me be honest: I don't get it perfect every day. Some days I sleep in. Some days I eat takeout. Some days I scroll mindlessly for an hour.

**And that's okay.**

Wellness isn't about perfection—it's about **awareness** and **course correction**. It's about noticing when you're off balance and gently guiding yourself back.

## A Note on Mental Health

Wellness includes mental health, and sometimes we need professional support. There's no shame in:
- Seeing a therapist
- Taking prescribed medication
- Asking for help
- Taking mental health days

Your mental health matters just as much as your physical health.

## Moving Forward

My wellness journey is ongoing. Some days are easier than others. But I've learned that the practices I've built are like anchors—they keep me steady when life gets stormy.

I invite you to start your own journey. Not tomorrow, not next Monday—today. With one small step. One deep breath. One moment of choosing yourself.

You're worth it.

---

**Your Turn:** What's one small wellness practice you could start today? Share in the comments—I'd love to cheer you on!

💝 *Remember: Progress, not perfection.*
`
  },
  {
    id: '04-art-of-slow-living',
    title: 'Art of slow living',
    content: `# The Art of Slow Living

In a culture that celebrates hustle, choosing slow is revolutionary. Here's how I learned to do less and live more.

## Table of Contents

- [What Is Slow Living?](#what-is-slow-living)
- [Why I Chose Slow](#why-i-chose-slow)
- [Principles of Slow Living](#principles-of-slow-living)
- [Practical Steps](#practical-steps)
- [The Beauty of Constraints](#the-beauty-of-constraints)
- [Your Slow Living Journey](#your-slow-living-journey)

## What Is Slow Living?

Slow living isn't about doing everything at a snail's pace. It's not laziness or lack of ambition. 

**Slow living is intentional living.**

It's about:
- 🐌 Doing things at the right speed, not the fastest
- 🎯 Prioritizing what matters, eliminating the rest
- 🌿 Savoring experiences instead of rushing through them
- 💭 Being present instead of perpetually distracted
- 🏡 Creating a life that feels good on the inside

> "Slow living is not about doing everything slowly. It's about doing everything at the right speed." — Unknown

### What Slow Living Is NOT

| Myth | Reality |
|------|---------|
| Being unproductive | Being intentionally productive |
| Having no goals | Having meaningful goals |
| Never being busy | Choosing when to be busy |
| Rejecting technology | Using technology mindfully |
| Living in isolation | Cultivating quality connections |

## Why I Chose Slow

My fast life looked successful from the outside:
- Packed calendar ✓
- Multiple projects ✓
- Always "on" ✓
- Exhausted but proud ✓

But inside, I was running on empty.

### The Breaking Point

I realized I hadn't truly *enjoyed* anything in months. I'd rush through experiences, already thinking about the next thing. I was collecting moments but not savoring them.

> "Almost everything will work again if you unplug it for a few minutes, including you." — Anne Lamott

### The Turning Point

One Sunday, I deliberately did nothing for an entire day. No plans, no productivity, no pressure. Just... being.

And something shifted.

I remembered what it felt like to:
- Read a book without checking my phone
- Drink coffee while watching the sunrise
- Think without distraction
- Simply exist without justification

## Principles of Slow Living

### 1. Intentionality

Everything I do is a choice. When I act with intention, I'm no longer on autopilot.

**Questions I Ask Myself:**
- Why am I doing this?
- Does this align with my values?
- What would happen if I didn't do this?
- Is this the best use of my time and energy?

### 2. Presence

Being here, now. Not dwelling on the past or worrying about the future.

\`\`\`mermaid
flowchart TD
    A[Moment Arises] --> B{Where Is Your Attention?}
    B -->|Past| C[Regret/Rumination]
    B -->|Future| D[Anxiety/Worry]
    B -->|Present| E[Peace/Engagement]
    C --> F[Mindfulness Practice]
    D --> F
    F --> E
\`\`\`

### 3. Simplicity

Less clutter, less noise, less everything that doesn't serve me.

**Areas I Simplified:**
- 🏠 Physical space (decluttering)
- 📱 Digital space (apps, notifications)
- 📅 Calendar (commitments)
- 🧠 Mental space (inputs, worries)
- 💬 Social (quality over quantity)

### 4. Quality Over Quantity

One meaningful experience beats ten shallow ones.

| Instead Of... | I Choose... |
|---------------|-------------|
| 10 casual acquaintances | 3 deep friendships |
| Scrolling 100 posts | Reading one good article |
| 5 rushed meals | 1 mindful meal |
| 10 mediocre projects | 1 excellent project |
| Busy every day | Margin for rest |

### 5. Connection

To myself, to others, to nature, to something bigger.

## Practical Steps

### Start Small

You don't need to quit your job and move to a cabin (unless you want to!). Here are gentle ways to begin:

#### Morning Adjustments

**Before:**
- ⏰ Alarm, immediately check phone
- 🏃 Rush through morning
- ☕ Coffee while multitasking
- 📱 Social media with breakfast

**After:**
- ⏰ Alarm, 5 minutes of breathing
- 🧘 Gentle stretching
- ☕ Coffee, just coffee
- 📖 Reading or journaling

#### Evening Adjustments

**Before:**
- 💻 Work until dinner
- 📺 Mindless TV scrolling
- 📱 Phone in bed
- 😴 Exhausted collapse into sleep

**After:**
- 🕐 Work ends at a set time
- 📖 Reading or gentle activity
- 📵 No screens before bed
- 😴 Peaceful transition to sleep

### The Art of Saying No

This was my hardest lesson. Here's my framework:

\`\`\`mermaid
flowchart TD
    A[Request/Invitation] --> B{Does This Excite Me?}
    B -->|Immediately Yes| C[Enthusiastic Yes]
    B -->|Uncertain| D[Sleep On It]
    B -->|No| E[Gracious No]
    D --> F{Next Day Feeling?}
    F -->|Still Excited| C
    F -->|Dread| E
    C --> G[No Resentment]
    E --> G
\`\`\`

### Creating Margin

Margin is the space between commitments. It's where life happens.

**How I Create Margin:**
- Buffer time between appointments (15 min minimum)
- One day per week with no plans
- Not scheduling every evening
- Leaving projects at 80% sometimes (perfectionism is exhausting)
- Defaulting to "no" when uncertain

## The Beauty of Constraints

Paradoxically, constraints create freedom. When I limit my options, I focus my energy.

### My Constraints

| Area | Constraint | Result |
|------|------------|--------|
| Phone | No social media before noon | Better mornings |
| Work | No emails after 6 PM | Better evenings |
| Commitments | Max 3 per week | More presence |
| Projects | Max 2 major projects | Better quality |
| Shopping | 30-day waiting period | Less clutter |

### The 80/20 Rule

80% of my fulfillment comes from 20% of my activities. Identifying that 20% was transformative.

**My 20%:**
- Creating content I'm proud of
- Deep conversations with loved ones
- Time in nature
- Reading and learning
- Rest and restoration

## Your Slow Living Journey

### Questions for Reflection

Grab a journal and explore:

1. What does "enough" look like to me?
2. Where am I rushing that I could slow down?
3. What commitments drain me? Which energize me?
4. What would I do if I couldn't post about it?
5. When do I feel most alive and present?

### A 7-Day Slow Living Challenge

| Day | Practice |
|-----|----------|
| 1 | No phone for first hour after waking |
| 2 | Eat one meal without any distractions |
| 3 | Take a 15-minute walk without destination |
| 4 | Say no to one non-essential commitment |
| 5 | Spend 30 minutes in nature |
| 6 | Do one thing with full attention (no multitasking) |
| 7 | Digital sunset—no screens after 8 PM |

### Common Obstacles (And Solutions)

**"I don't have time"**
→ Start with 5 minutes. Everyone has 5 minutes.

**"My job requires me to be fast"**
→ Slow living is about *how* you do things, not speed of completion.

**"I'll fall behind"**
→ Behind whom? You're running your own race.

**"People will think I'm lazy"**
→ Their opinion matters less than your wellbeing.

**"I've tried before and failed"**
→ This isn't failure—it's practice. Try again, gentler.

## The Ripple Effect

When I slowed down, something unexpected happened:

- My work improved (more focus = better quality)
- My relationships deepened (more presence = more connection)
- My creativity returned (space = inspiration)
- My health improved (less stress = better body function)

> "When you slow down, you don't accomplish less—you accomplish with greater intention." — Unknown

## A Letter to My Former Fast-Living Self

Dear Hurried Me,

I know you think speed equals success. I know you believe rest is for later. I know you're afraid that slowing down means falling behind.

But I promise you: the best things in life can't be rushed.

The perfect cup of tea.
The deep conversation with a friend.
The creative breakthrough.
The moment of clarity.
The feeling of truly being alive.

None of these happen at speed.

Trust me. Slow down. You won't miss out—you'll finally be present for what matters.

With love,  
Your Slower Self

---

**Your Invitation:** Choose one area of your life to slow down this week. Just one. Notice what happens.

🌿 *Slow is smooth. Smooth is fast. And peaceful is priceless.*
`
  },
  {
    id: '05-creative-confidence',
    title: 'Creative confidence',
    content: `# Creative Confidence: Unlocking Your Inner Artist

Creativity isn't a talent—it's a way of living. Here's how I rediscovered my creative voice and learned that everyone is an artist.

## Table of Contents

- [The Creativity Myth](#the-creativity-myth)
- [My Creative Awakening](#my-creative-awakening)
- [What Is Creative Confidence?](#what-is-creative-confidence)
- [Blocks to Creativity](#blocks-to-creativity)
- [Building Creative Confidence](#building-creative-confidence)
- [Daily Creative Practice](#daily-creative-practice)
- [Your Creative Journey](#your-creative-journey)

## The Creativity Myth

Here's what I used to believe:

> "Some people are born creative. I'm not one of them."

Sound familiar? This myth keeps so many of us from exploring our creative potential.

### The Truth About Creativity

| Myth | Truth |
|------|-------|
| Creativity is a gift | Creativity is a practice |
| Artists are special | Everyone creates |
| You need talent | You need curiosity |
| It's about the product | It's about the process |
| Perfection is the goal | Expression is the goal |

> "Creativity is not a talent. It is a way of operating." — John Cleese

### Creativity Is Human

Think about it:
- Cooking dinner = creativity
- Decorating your space = creativity
- Problem-solving at work = creativity
- Telling stories to friends = creativity
- Gardening = creativity
- Parenting = creativity

We're all creators. We just forgot.

## My Creative Awakening

### The Childhood Artist

As a kid, I created without hesitation:
- 🎨 Doodles on every surface
- 📝 Stories in colorful notebooks
- 🎭 Dramatic performances for family
- 🏗️ Forts built from furniture
- 🎵 Songs made up on the spot

No fear. No judgment. Just pure expression.

### The Lost Years

Then somewhere along the way:
- Someone said my drawing wasn't "right"
- Someone said I should be "practical"
- I compared my work to "real artists"
- I started valuing productivity over play
- I forgot what it felt like to create for joy

### The Return

My creative reawakening happened accidentally:

I bought a cheap watercolor set "for fun." My first attempts were... not good. But something magical happened—I didn't care. I was having *fun*.

> "The desire to create is one of the deepest yearnings of the human soul." — Dieter F. Uchtdorf

That's when I remembered: **Creativity isn't about being good. It's about being alive.**

## What Is Creative Confidence?

Creative confidence is the belief that you can make something meaningful.

### The Four Components

\`\`\`mermaid
flowchart TB
    subgraph CreativeConfidence["Creative Confidence"]
        direction TB
        Courage[Courage<br/>To begin]
        Curiosity[Curiosity<br/>To explore]
        Consistency[Consistency<br/>To practice]
        Compassion[Compassion<br/>For the process]
    end
    
    Courage --> Curiosity
    Curiosity --> Consistency
    Consistency --> Compassion
    Compassion --> Courage
\`\`\`

### Courage
The willingness to start before you're ready.

### Curiosity  
The desire to explore without knowing the outcome.

### Consistency
Showing up even when inspiration doesn't.

### Compassion
Being kind to yourself when it doesn't work out.

## Blocks to Creativity

### The Inner Critic

We all have one. Mine sounds suspiciously like my seventh-grade art teacher.

**Common Critic Statements:**
- "This isn't good enough"
- "Someone already did this better"
- "What's the point?"
- "You're wasting time"
- "Real artists don't struggle like this"

### Taming the Critic

Instead of fighting the critic, I learned to acknowledge it:

\`\`\`mermaid
flowchart TD
    A[Inner Critic Speaks] --> B[Acknowledge It]
    B --> C[Thank It for Trying to Help]
    C --> D[Choose to Create Anyway]
    D --> E[Focus on Process, Not Outcome]
    E --> F[Critic Gets Quieter Over Time]
\`\`\`

**My Response to the Critic:**
> "I hear you. You're trying to protect me from judgment. But I'm creating anyway, because this matters to me."

### Other Common Blocks

| Block | What It Feels Like | Antidote |
|-------|-------------------|----------|
| Perfectionism | "It must be flawless" | Done is better than perfect |
| Comparison | "They're so much better" | Compare only to your past self |
| Fear | "What if people hate it?" | Create for yourself first |
| Overwhelm | "I don't know where to start" | Tiny first step |
| Impatience | "I should be better by now" | Trust the process |

## Building Creative Confidence

### Start Before You're Ready

This is the secret. There is no "ready."

**My First Projects:**
- Terrible poems no one saw
- Blurry photos I kept anyway
- Ugly pottery I'm proud of
- Bad drawings that taught me something

Every master was once a disaster. The difference? They kept going.

### Create a Safe Space

I have a corner of my home where:
- Mess is allowed
- Judgment doesn't enter
- Experiments are celebrated
- "Failures" are just data

You need this space too. It can be:
- A physical corner
- A digital folder
- A time of day
- A mindset

### The Power of Constraints

Paradoxically, limitations boost creativity:

**Try These:**
- Create with only 3 colors
- Write in exactly 100 words
- Photograph only things within 1 meter
- Draw with your non-dominant hand
- Make art in 10 minutes

Constraints force creative problem-solving.

## Daily Creative Practice

### My Morning Pages

Every morning, I write 3 pages of stream-of-consciousness thoughts.

**Rules:**
1. Write without stopping
2. Don't edit or judge
3. Don't show anyone
4. Just let it flow

This practice:
- Clears mental clutter
- Uncovers hidden ideas
- Builds creative muscle
- Starts the day centered

### The 15-Minute Rule

I commit to just 15 minutes of creative time daily.

**Why It Works:**
- Low barrier to entry
- Builds consistency
- Often leads to longer sessions
- Removes the pressure of "big projects"

\`\`\`mermaid
flowchart LR
    A[Commit to 15 Min] --> B[Start Creating]
    B --> C{After 15 Min?}
    C -->|Want to Continue| D[Keep Going]
    C -->|Done| E[Stop Without Guilt]
    D --> F[Next Day Easier]
    E --> F
\`\`\`

### Weekly Creative Dates

Once a week, I have a creative date with myself:
- 1-2 hours of uninterrupted time
- No agenda or expectations
- Just exploration and play
- Often my best ideas emerge here

## Finding Your Medium

Not sure what to create? Try this:

### The Curiosity Audit

Ask yourself:

1. **What did I love as a child?**
   - Drawing? Writing? Building? Performing?

2. **What do I enjoy consuming?**
   - Love reading? Try writing.
   - Love galleries? Try painting.
   - Love concerts? Try music.

3. **What makes me lose track of time?**
   - This is a clue to your creative flow

4. **What would I do if I couldn't fail?**
   - The fear points to the passion

### Permission to Dabble

You don't have to pick one thing forever. I've been:
- A photographer (still am!)
- A poet (sometimes still)
- A potter (terrible but joyful)
- A gardener (ongoing experiment)
- A cook (deliciously learning)

**Dabbling is not quitting—it's exploring.**

## The Creative Cycle

Understanding this saved my sanity:

\`\`\`mermaid
flowchart TD
    A[Inspiration] --> B[Creation]
    B --> C[Completion]
    C --> D[Rest]
    D --> E[Incubation]
    E --> A
    
    style D fill:#90EE90
    style E fill:#90EE90
\`\`\`

**The phases:**

1. **Inspiration** - The spark, the idea
2. **Creation** - The work, the flow
3. **Completion** - Finishing, sharing
4. **Rest** - Recovery, emptiness (this is normal!)
5. **Incubation** - Subconscious processing

Most people quit at Rest, thinking they've lost their creativity. They haven't—they're just in a necessary phase.

## Sharing Your Work

This is scary. Do it anyway.

### Why Share?

- Connects you with others
- Creates accountability
- Inspires someone else
- Completes the creative cycle
- Builds confidence

### Start Small

- Share with one trusted friend
- Post in a supportive community
- Create a private Instagram for your work
- Join a local creative group
- Start a blog (like this one!)

> "You don't have to be great to start, but you have to start to be great." — Zig Ziglar

## Your Creative Journey

### Questions for Reflection

1. When did I stop creating?
2. What creative activities did I love as a child?
3. What's one tiny creative act I could do today?
4. What would I create if no one would ever see it?
5. What's stopping me? (Be honest)

### A 7-Day Creative Challenge

| Day | Practice |
|-----|----------|
| 1 | Doodle for 5 minutes (stick figures count!) |
| 2 | Write a 6-word story |
| 3 | Take one photo of something beautiful |
| 4 | Make something with your hands |
| 5 | Rearrange something in your space |
| 6 | Try a creative activity you've never done |
| 7 | Share something you created (anywhere) |

### Remember This

- Your creativity is valid, regardless of skill
- The world needs your unique perspective
- Done is better than perfect
- Comparison kills creativity
- Play is productive
- You're allowed to make bad art
- The process is the point

---

## A Letter to Aspiring Creators

Dear Beautiful Soul,

I know you're afraid. I know the critic is loud. I know you're worried it won't be good enough.

Create anyway.

Not because you'll be discovered. Not because you'll be famous. Not because you'll be the best.

Create because it makes you feel alive. Because the world needs what only you can make. Because your future self will thank you.

Start messy. Start small. Start scared. Just start.

You're an artist. I promise.

With belief in you,  
*Naranyala*

---

**Your Turn:** What's one tiny creative thing you'll do today? Tell me in the comments—I'm cheering for you!

🎨 *Remember: Every artist was first an amateur. Every masterpiece began as a mess. Begin anyway.*
`
  },
  {
    id: '06-photography-journey',
    title: 'Photography journey',
    content: `# The Photography Bug: Capturing Life's Beautiful Moments

Photography changed how I see the world. Here's my journey from point-and-shoot to finding beauty in everyday moments.

## Table of Contents

- [How It Started](#how-it-started)
- [Why Photography?](#why-photography)
- [My Gear Journey](#my-gear-journey)
- [Finding Your Eye](#finding-your-eye)
- [Composition Basics](#composition-basics)
- [The Magic of Golden Hour](#the-magic-of-golden-hour)
- [Street Photography Adventures](#street-photography-adventures)
- [Tips for Beginners](#tips-for-beginners)

## How It Started

I didn't set out to become a photographer. It happened accidentally.

### The First Camera

My first "real" camera was a hand-me-down DSLR from a friend who was upgrading. It was heavy, complicated, and I had no idea what I was doing.

**My First Photos:**
- Blurry shots of my coffee
- Overexposed pictures of the sky
- Random objects around my apartment
- A lot of accidental butt-dial photos (the camera was always on)

> "Your first 10,000 photographs are your worst." — Ansel Adams

I now know Ansel Adams was being generous. My first 10,000 were truly terrible.

### The Moment It Clicked

Then one evening, I captured something magical:

Golden light streaming through my kitchen window. Dust particles dancing in the beam. A simple moment, but through the lens, it looked... extraordinary.

That's when I realized: **Photography isn't about the camera. It's about seeing.**

## Why Photography?

### It Slows Me Down

In a fast world, photography forces me to pause:
- To notice the light
- To observe the details
- To appreciate the moment
- To be present

### It Changes My Perspective

Suddenly, I'm looking at:
- How light falls on a wall
- The geometry of buildings
- Expressions on strangers' faces
- Patterns in nature
- Colors I never noticed

### It Preserves Memories

Photos are time machines. They transport me back to:
- The smell of rain that day
- The feeling of being there
- The conversation I was having
- The person I was then

## My Gear Journey

### What I've Used

| Camera | When | What I Learned |
|--------|------|----------------|
| Smartphone | Still use! | Best camera is the one you have |
| Entry DSLR | First "real" camera | Technical basics |
| Mirrorless | Current daily | Portability matters |
| Film camera | Weekend fun | Intentionality |
| Drone | Special occasions | New perspectives |

### Current Setup

**For Daily Carry:**
- 📷 Mirrorless camera with 35mm lens
- 📱 Smartphone (always with me)
- 🎒 Small, comfortable bag

**For Special Shoots:**
- 📷 Full-frame mirrorless
- 🔍 Multiple lenses (24-70mm, 50mm, 85mm)
- 🎯 Tripod for long exposures
- 🔋 Extra batteries (always!)

### The Truth About Gear

**Expensive gear doesn't make you better.**

I've seen stunning photos from:
- iPhone photographers
- Disposable cameras
- Old film cameras
- Budget DSLRs

And boring photos from:
- Top-of-the-line cameras
- Every lens imaginable
- Perfect lighting setups

**Your eye matters more than your equipment.**

## Finding Your Eye

### What Makes a Photo "Yours"?

Your style isn't something you choose—it's something that emerges.

**My Style Evolved Through:**
- Shooting what I love (not what's trendy)
- Editing consistently (similar tones, colors)
- Studying photographers I admire
- Practicing daily
- Reviewing my work honestly

### Subjects That Call to Me

| Subject | Why I Love It |
|---------|---------------|
| Street scenes | Candid human moments |
| Landscapes | Nature's grandeur |
| Portraits | Connection and story |
| Architecture | Geometry and light |
| Details | Beauty in small things |

### Exercise: Find Your Focus

Try this for one week:
- Day 1: Photograph only blue things
- Day 2: Only shadows
- Day 3: Only textures
- Day 4: Only movement
- Day 5: Only stillness
- Day 6: Only things that make you smile
- Day 7: Review—what felt most natural?

## Composition Basics

### Rule of Thirds

The classic for a reason:

\`\`\`mermaid
flowchart TB
    subgraph Frame["Photo Frame"]
        direction TB
        A[Top Third] --> B[Middle Third]
        B --> C[Bottom Third]
    end
    
    subgraph Vertical["Vertical Thirds"]
        direction LR
        D[Left Third] --> E[Middle Third]
        E --> F[Right Third]
    end
    
    Frame -.-> Vertical
    
    style A fill:#e0e0e0
    style C fill:#e0e0e0
    style D fill:#e0e0e0
    style F fill:#e0e0e0
\`\`\`

**How to Use:**
- Place subjects at intersection points
- Align horizons with third lines
- Break the rule intentionally (not accidentally)

### Leading Lines

Lines guide the viewer's eye:
- Roads
- Fences
- Shadows
- Architecture
- Shorelines

### Framing

Use elements to frame your subject:
- Windows
- Doorways
- Tree branches
- Arches
- Gaps in crowds

### Negative Space

Sometimes what you don't include matters most:
- Empty sky
- Blank walls
- Water
- Shadows
- Distance

## The Magic of Golden Hour

### What Is Golden Hour?

The period shortly after sunrise or before sunset when light is soft, warm, and magical.

**Why Photographers Love It:**
- Soft, diffused light
- Warm, golden tones
- Long, dramatic shadows
- Flattering for portraits
- Makes everything look cinematic

### My Golden Hour Routine

\`\`\`mermaid
flowchart LR
    A[Check Sunset Time] --> B[Arrive 1 Hour Early]
    B --> C[Scout Locations]
    C --> D[Set Up Equipment]
    D --> E[Shoot During Golden Hour]
    E --> F[Stay for Blue Hour]
    F --> G[Review & Celebrate]
\`\`\`

### Blue Hour Bonus

Stick around after sunset for blue hour:
- Deep blue sky
- City lights turn on
- Moody, atmospheric shots
- Less crowded locations

## Street Photography Adventures

### Overcoming the Fear

Street photography terrified me at first. Photographing strangers felt... intrusive.

**What Changed My Mind:**
- Most people don't notice
- Those who do often smile
- It's public space—it's legal
- I'm documenting life, not exploiting
- Respect goes a long way

### Street Photography Etiquette

| Do | Don't |
|----|-------|
| Be respectful | Be creepy |
| Smile if noticed | Stare aggressively |
| Move on if asked | Argue about rights |
| Capture moments | Stage scenes |
| Blend in | Be obvious |

### My Best Street Photos

The ones I'm proud of capture:
- Genuine laughter
- Quiet contemplation
- Unexpected juxtapositions
- Light and shadow play
- Human connection

## Tips for Beginners

### Technical Basics

**The Exposure Triangle:**

\`\`\`mermaid
flowchart TB
    subgraph Exposure["Exposure Triangle"]
        direction TB
        Aperture[Aperture<br/>Depth of Field]
        Shutter[Shutter Speed<br/>Motion]
        ISO[ISO<br/>Sensitivity]
    end
    
    Aperture --> Exposure
    Shutter --> Exposure
    ISO --> Exposure
\`\`\`

1. **Aperture** - Controls depth of field
   - Low f-number (f/1.8) = blurry background
   - High f-number (f/16) = everything sharp

2. **Shutter Speed** - Controls motion
   - Fast (1/1000s) = freeze action
   - Slow (1/30s) = motion blur

3. **ISO** - Controls sensitivity
   - Low (100) = clean, needs light
   - High (3200) = grainy, low light

### Practical Tips

**Before You Shoot:**
- Charge batteries
- Clear memory cards
- Check the weather
- Scout locations online

**While Shooting:**
- Shoot in RAW if possible
- Take multiple versions
- Try different angles
- Look for light first

**After Shooting:**
- Back up immediately
- Cull ruthlessly
- Edit consistently
- Share selectively

### Learning Resources

**Books That Helped Me:**
- "Understanding Exposure" by Bryan Peterson
- "The Photographer's Eye" by Michael Freeman
- "On Photography" by Susan Sontag

**Photographers I Study:**
- Henri Cartier-Bresson (street)
- Annie Leibovitz (portraits)
- Ansel Adams (landscape)
- Vivian Maier (street)
- Steve McCurry (documentary)

**Free Online Resources:**
- YouTube tutorials
- Photography subreddits
- Instagram for inspiration
- Local photography meetups

## The Editing Process

### My Workflow

\`\`\`mermaid
flowchart LR
    A[Import Photos] --> B[Initial Cull]
    B --> C[Select Favorites]
    C --> D[Basic Adjustments]
    D --> E[Fine-Tune]
    E --> F[Export]
    F --> G[Share/Archive]
\`\`\`

### Software I Use

- **Lightroom** - Organization and batch editing
- **Photoshop** - Detailed retouching
- **VSCO** - Mobile editing
- **Snapseed** - Quick phone edits

### Editing Philosophy

**My Rules:**
1. Enhance, don't fix
2. Stay true to the moment
3. Develop a consistent style
4. Know when to stop
5. The photo should work before editing

## Finding Your Voice

### Questions to Ask Yourself

1. What do I want people to feel?
2. What stories am I drawn to?
3. What makes me pick up my camera?
4. What would I photograph if no one saw it?
5. What do I see that others miss?

### Your Style Will Emerge

Don't force it. Just:
- Shoot what you love
- Study what inspires you
- Practice consistently
- Review your work
- Trust the process

## The Business Side (Optional)

### Should You Monetize?

I get asked this often. My answer: **Maybe.**

**Consider Monetizing If:**
- You love the pressure
- You're business-minded
- You can separate art from income
- You have a unique offering

**Keep It as a Hobby If:**
- Photography is your stress relief
- You value creative freedom
- You don't want client demands
- You shoot what you want, when you want

I chose hobby. No regrets.

## Final Thoughts

Photography has given me:
- A reason to explore
- A way to see beauty everywhere
- A community of fellow enthusiasts
- A record of my life
- A meditation practice

You don't need the best gear. You don't need formal training. You don't need permission.

You just need to start.

---

**Your Assignment:** Take your camera (or phone) today and photograph one thing that makes you smile. That's it. That's the assignment.

📸 *Remember: The best camera is the one you have with you. The second-best is the one you're learning to use well.*

---

*What's your photography journey? I'd love to see your work—tag me on social media!*
`
  },
  {
    id: '07-creative-workflow',
    title: 'Creative workflow',
    content: `# My Creative Workflow

A behind-the-scenes look at how I create content, from inspiration to publication.

## Table of Contents

- [My Creative Process](#my-creative-process)
- [Tools I Use](#tools-i-use)
- [Code Examples](#code-examples)
- [Workflow Diagrams](#workflow-diagrams)

## My Creative Process

Creating content is both an art and a science. Here's my systematic approach to bringing ideas to life.

### Phase 1: Inspiration

Inspiration strikes in unexpected moments. I capture ideas using:

- Morning pages (stream of consciousness writing)
- Photo walks with my camera
- Conversations with interesting people
- Books, podcasts, and documentaries

### Phase 2: Planning

Once I have an idea, I structure it:

\`\`\`typescript
interface ContentPlan {
  title: string;
  category: 'travel' | 'lifestyle' | 'creative' | 'growth';
  outline: string[];
  assets: {
    photos: number;
    videos: number;
    graphics: number;
  };
  deadline: Date;
}

function createContentPlan(title: string): ContentPlan {
  return {
    title,
    category: 'lifestyle',
    outline: ['Introduction', 'Main Content', 'Conclusion'],
    assets: {
      photos: 10,
      videos: 2,
      graphics: 3,
    },
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 1 week
  };
}
\`\`\`

## Tools I Use

### Photography Stack

\`\`\`bash
# My photo editing workflow
#!/bin/bash

echo "Starting photo editing session..."

# Import photos from SD card
rsync -av /Volumes/SD_CARD/ ./photos/raw/

# Create backups
cp -r ./photos/raw/ ./photos/backup/

# Open Lightroom
open -A "Adobe Lightroom Classic"

echo "Ready to edit!"
\`\`\`

### Blog Deployment

\`\`\`python
#!/usr/bin/env python3
"""
Automated blog deployment script
"""

import subprocess
import sys
from datetime import datetime

def deploy_blog():
    """Build and deploy the blog"""
    print(f"🚀 Starting deployment at {datetime.now()}")
    
    # Build the project
    result = subprocess.run(['bun', 'run', 'build'], 
                          capture_output=True, 
                          text=True)
    
    if result.returncode != 0:
        print(f"❌ Build failed: {result.stderr}")
        sys.exit(1)
    
    print("✅ Build successful!")
    
    # Deploy to server
    subprocess.run(['rsync', '-avz', 'dist/', 'user@server:/var/www/blog/'])
    
    print(f"🎉 Deployment complete at {datetime.now()}")

if __name__ == '__main__':
    deploy_blog()
\`\`\`

## Workflow Diagrams

### Content Creation Flow

Here's my complete content creation workflow:

\`\`\`mermaid
flowchart TD
    A[Inspiration] --> B{Idea Worth Pursuing?}
    B -->|No| C[Discard]
    B -->|Yes| D[Planning]
    D --> E[Content Creation]
    E --> F{Content Type?}
    F -->|Blog Post| G[Writing & Photography]
    F -->|Photo Essay| H[Photo Selection & Editing]
    F -->|Video| I[Recording & Editing]
    G --> J[Review & Edit]
    H --> J
    I --> J
    J --> K{Ready to Publish?}
    K -->|No| E
    K -->|Yes| L[Publish]
    L --> M[Share on Social Media]
    M --> N[Engage with Audience]
    N --> O[Analyze Performance]
    O --> P[Learn & Improve]
    P --> A
\`\`\`

### Photo Editing Workflow

My detailed photo editing process:

\`\`\`mermaid
graph TB
    subgraph Import["Import Phase"]
        A1[SD Card] --> A2[Copy to Computer]
        A2 --> A3[Backup to External Drive]
        A3 --> A4[Import to Lightroom]
    end
    
    subgraph Cull["Culling Phase"]
        B1[Review All Photos] --> B2[Select Keepers]
        B2 --> B3[Rate 1-5 Stars]
        B3 --> B4[Flag Best Shots]
    end
    
    subgraph Edit["Editing Phase"]
        C1[Basic Adjustments] --> C2[Color Grading]
        C2 --> C3[Local Adjustments]
        C3 --> C4[Export]
    end
    
    subgraph Deliver["Delivery Phase"]
        D1[Blog Post] --> D2[Social Media]
        D2 --> D3[Portfolio]
    end
    
    Import --> Cull
    Cull --> Edit
    Edit --> Deliver
\`\`\`

### Publishing Pipeline

The technical side of publishing:

\`\`\`mermaid
sequenceDiagram
    participant Author
    participant Git
    participant Build
    participant Server
    participant CDN
    
    Author->>Git: git push
    Git->>Build: Trigger build
    Build->>Build: Install dependencies
    Build->>Build: Run tests
    Build->>Build: Build site
    Build->>Server: Deploy artifacts
    Server->>CDN: Invalidate cache
    CDN-->>Author: Deployment complete
\`\`\`

## Code Examples

### Responsive Image Component

Here's how I handle responsive images in my blog:

\`\`\`typescript
import { Component, Input } from '@angular/core';

interface ImageSrc {
  url: string;
  width: number;
}

@Component({
  selector: 'app-responsive-image',
  template: \`
    <img
      [src]="defaultSrc"
      [srcset]="srcset"
      [sizes]="sizes"
      [alt]="alt"
      loading="lazy"
      class="responsive-image"
    />
  \`,
  styles: [\`
    .responsive-image {
      max-width: 100%;
      height: auto;
      display: block;
    }
  \`],
})
export class ResponsiveImageComponent {
  @Input() images: ImageSrc[] = [];
  @Input() alt = '';
  @Input() sizes = '(max-width: 768px) 100vw, 50vw';
  
  get defaultSrc(): string {
    return this.images[0]?.url || '';
  }
  
  get srcset(): string {
    return this.images
      .map(img => \`\${img.url} \${img.width}w\`)
      .join(', ');
  }
}

// Usage:
// <app-responsive-image
//   [images]="[
//     { url: 'photo-400.jpg', width: 400 },
//     { url: 'photo-800.jpg', width: 800 },
//     { url: 'photo-1200.jpg', width: 1200 }
//   ]"
//   alt="Beautiful landscape"
// />
\`\`\`

### Social Media Scheduler

I automate my social media posting:

\`\`\`javascript
/**
 * Schedule social media posts across platforms
 */
class SocialMediaScheduler {
  constructor(apiKeys) {
    this.apiKeys = apiKeys;
    this.platforms = ['twitter', 'instagram', 'facebook'];
  }

  async schedulePost(content, platforms, scheduleTime) {
    const posts = [];

    for (const platform of platforms) {
      const post = {
        platform,
        content: this.formatForPlatform(content, platform),
        scheduledFor: scheduleTime,
        status: 'pending',
      };

      posts.push(this.createPost(post));
    }

    return Promise.all(posts);
  }

  formatForPlatform(content, platform) {
    switch (platform) {
      case 'twitter':
        return content.slice(0, 280);
      case 'instagram':
        return content + '\n\n#blog #lifestyle #creativity';
      case 'facebook':
        return content;
      default:
        return content;
    }
  }

  async createPost(post) {
    console.log(\`Scheduling \${post.platform} post for \${post.scheduledFor}\`);
    // API call would go here
    return { id: Math.random().toString(36), ...post };
  }
}

// Usage
const scheduler = new SocialMediaScheduler(apiKeys);
await scheduler.schedulePost(
  'New blog post is live! Check out my creative workflow...',
  ['twitter', 'instagram', 'facebook'],
  new Date('2026-04-01T09:00:00Z')
);
\`\`\`

## Project Structure

Here's how I organize my blog project:

\`\`\`
naravisuals-web/
├── src/
│   ├── app/
│   │   ├── article/
│   │   │   ├── components/
│   │   │   │   ├── article-reader/
│   │   │   │   ├── article-list/
│   │   │   │   ├── code-block/
│   │   │   │   └── mermaid-diagram/
│   │   │   └── services/
│   │   ├── shared/
│   │   │   ├── components/
│   │   │   ├── services/
│   │   │   └── utils/
│   │   └── app.component.ts
│   ├── assets/
│   ├── docs/ (markdown articles)
│   └── main.ts
├── scripts/
│   └── generate-articles.ts
└── package.json
\`\`\`

## Lessons Learned

Through this workflow, I've discovered:

1. **Consistency beats intensity** - Regular creation is better than bursts
2. **Systems enable creativity** - Good processes free mental space
3. **Automation saves time** - Script repetitive tasks
4. **Feedback improves quality** - Share early, iterate often
5. **Rest is productive** - Breaks lead to better ideas

---

**Your Turn:** What does your creative workflow look like? I'd love to hear about your process!

*Share your thoughts in the comments or tag me on social media!*
`
  },
  {
    id: '08-mermaid-examples',
    title: 'Mermaid examples',
    content: `# Mermaid.js Diagram Examples

A comprehensive showcase of all Mermaid diagram types you can use in your markdown articles.

## Table of Contents

- [Flowcharts](#flowcharts)
- [Sequence Diagrams](#sequence-diagrams)
- [Class Diagrams](#class-diagrams)
- [State Diagrams](#state-diagrams)
- [Gantt Charts](#gantt-charts)
- [Pie Charts](#pie-charts)
- [Mind Maps](#mind-maps)
- [Timeline](#timeline)

## Flowcharts

Flowcharts are perfect for showing processes, workflows, and decision trees.

### Basic Flowchart

\`\`\`mermaid
flowchart TD
    A[Start] --> B{Is it working?}
    B -->|Yes| C[Great!]
    B -->|No| D{Did you try turning it off and on?}
    D -->|Yes| E[Have you tried updating?]
    D -->|No| F[Turn it off and on]
    E -->|Yes| G[Time to buy a new one]
    E -->|No| H[Update it]
    F --> B
    H --> B
    C --> I[End]
    G --> I
\`\`\`

### Complex Process Flow

\`\`\`mermaid
flowchart LR
    subgraph Planning["Planning Phase"]
        A1[Research] --> A2[Outline]
        A2 --> A3[Gather Assets]
    end
    
    subgraph Creation["Creation Phase"]
        B1[Write Draft] --> B2[Add Images]
        B2 --> B3[Format Content]
    end
    
    subgraph Review["Review Phase"]
        C1[Self Review] --> C2[Peer Review]
        C2 --> C3[Final Edits]
    end
    
    subgraph Publish["Publishing Phase"]
        D1[Upload] --> D2[SEO Optimize]
        D2 --> D3[Publish]
    end
    
    Planning --> Creation
    Creation --> Review
    Review --> Publish
\`\`\`

### Decision Tree

\`\`\`mermaid
flowchart TD
    Start[New Blog Post] --> Topic{Topic Chosen?}
    Topic -->|No| Research[Research Trends]
    Topic -->|Yes| Outline[Create Outline]
    Research --> Topic
    Outline --> Content{Content Type?}
    Content -->|Tutorial| Code[Add Code Examples]
    Content -->|Story| Photos[Add Photos]
    Content -->|Guide| Both[Add Both]
    Code --> Edit[Edit Content]
    Photos --> Edit
    Both --> Edit
    Edit --> Publish[Publish!]
\`\`\`

## Sequence Diagrams

Sequence diagrams show interactions between entities over time.

### Blog Publishing Flow

\`\`\`mermaid
sequenceDiagram
    participant Author
    participant CMS
    participant Build
    participant Server
    participant CDN
    
    Author->>CMS: Create Draft
    CMS-->>Author: Draft Saved
    Author->>CMS: Submit for Review
    CMS->>Build: Trigger Build
    Build->>Build: Install Dependencies
    Build->>Build: Compile Assets
    Build->>Build: Optimize Images
    Build->>Server: Deploy Files
    Server->>CDN: Invalidate Cache
    CDN-->>Author: Live!
\`\`\`

### User Authentication

\`\`\`mermaid
sequenceDiagram
    autonumber
    User->>Login Page: Enter Credentials
    Login Page->>API: POST /login
    API->>Database: Verify User
    Database-->>API: User Data
    API->>API: Validate Password
    API-->>Login Page: JWT Token
    Login Page->>Local Storage: Save Token
    Local Storage-->>User: Dashboard
\`\`\`

## Class Diagrams

Class diagrams show the structure of systems.

### Blog System Architecture

\`\`\`mermaid
classDiagram
    class Article {
        +string id
        +string title
        +string content
        +Date publishedAt
        +publish()
        +update()
    }
    
    class Author {
        +string id
        +string name
        +string email
        +getArticles()
        +writeArticle()
    }
    
    class Comment {
        +string id
        +string content
        +Date createdAt
        +approve()
        +delete()
    }
    
    class Category {
        +string id
        +string name
        +getArticles()
    }
    
    Author "1" --> "*" Article
    Article "1" --> "*" Comment
    Article "*" --> "*" Category
\`\`\`

## State Diagrams

State diagrams show the lifecycle of entities.

### Article Lifecycle

\`\`\`mermaid
stateDiagram-v2
    [*] --> Draft
    Draft --> Review: Submit
    Review --> Draft: Request Changes
    Review --> Approved: Approve
    Review --> Rejected: Reject
    Approved --> Scheduled: Schedule
    Scheduled --> Published: Publish Time
    Published --> Archived: Archive
    Published --> Updated: Edit
    Updated --> Published
    Archived --> [*]
    Rejected --> [*]
\`\`\`

### User Journey

\`\`\`mermaid
stateDiagram-v2
    [*] --> Visitor
    Visitor --> Subscriber: Subscribe
    Subscriber --> Reader: Read Article
    Reader --> Subscriber: Finish Reading
    Reader --> Commenter: Comment
    Commenter --> Reader: Submit Comment
    Subscriber --> Follower: Follow on Social
    Follower --> [*]
\`\`\`

## Gantt Charts

Gantt charts show project timelines.

### Blog Content Calendar

\`\`\`mermaid
gantt
    title Blog Content Schedule - April 2026
    dateFormat  YYYY-MM-DD
    section Week 1
    Research Topics      :a1, 2026-04-01, 2d
    Write Draft          :a2, after a1, 3d
    Add Images           :a3, after a2, 2d
    section Week 2
    Edit Content         :b1, 2026-04-08, 2d
    SEO Optimization     :b2, after b1, 1d
    Publish              :b3, after b2, 1d
    section Week 3
    Social Media Posts   :c1, 2026-04-15, 3d
    Engage Comments      :c2, after c1, 4d
    section Week 4
    Analytics Review     :d1, 2026-04-22, 2d
    Plan Next Month      :d2, after d1, 3d
\`\`\`

### Project Timeline

\`\`\`mermaid
gantt
    title Website Redesign Project
    dateFormat  YYYY-MM-DD
    axisFormat  %b %d
    
    Design Phase       :des1, 2026-04-01, 7d
    Frontend Dev       :dev1, after des1, 10d
    Backend Dev        :dev2, after des1, 8d
    Testing            :test, after dev1 dev2, 5d
    Launch             :launch, after test, 2d
\`\`\`

## Pie Charts

Pie charts show proportions.

### Content Distribution

\`\`\`mermaid
pie title Blog Content by Category
    "Travel" : 25
    "Lifestyle" : 30
    "Creative" : 20
    "Growth" : 15
    "Tech" : 10
\`\`\`

### Time Allocation

\`\`\`mermaid
pie title Weekly Time Allocation
    "Writing" : 20
    "Photography" : 15
    "Editing" : 10
    "Social Media" : 8
    "Email" : 5
    "Learning" : 7
\`\`\`

## Mind Maps

Mind maps organize ideas hierarchically.

### Content Strategy

\`\`\`mermaid
mindmap
  root((Content Strategy))
    Planning
      Research
      Keywords
      Calendar
    Creation
      Writing
      Photography
      Video
    Distribution
      Blog
      Social Media
      Newsletter
    Engagement
      Comments
      Email Replies
      Social Interactions
\`\`\`

### Blog Topics

\`\`\`mermaid
mindmap
  root((Blog Topics))
    Travel
      Destinations
      Tips
      Gear
    Lifestyle
      Wellness
      Home
      Routines
    Creative
      Photography
      Design
      Tutorials
    Personal Growth
      Productivity
      Mindset
      Learning
\`\`\`

## Timeline

Timelines show events in chronological order.

### My Blog Journey

\`\`\`mermaid
timeline
    title My Blogging Journey
    2020 : Started Blog
           : First 10 Posts
    2021 : Reached 1K Readers
           : Added Photography
    2022 : Launched Newsletter
           : 10K Monthly Views
    2023 : Redesigned Site
           : Added Video Content
    2024 : Monetization
           : Sponsorship Deals
    2025 : Full-Time Blogging
           : Team of 3
    2026 : New Platform
           : Mobile App
\`\`\`

## Combining Diagrams

You can use multiple diagrams in one article:

\`\`\`mermaid
flowchart TD
    A[Start Article] --> B{Type?}
    B -->|Tutorial| C[Add Code Blocks]
    B -->|Story| D[Add Photos]
    B -->|Guide| E[Add Diagrams]
    C --> F[Publish]
    D --> F
    E --> F
\`\`\`

---

## How to Use

1. **Choose the right diagram type** for your data
2. **Use code fences** with \`mermaid\` language
3. **Keep it simple** - don't overcrowd
4. **Test rendering** on mobile and desktop

## Tips

- **Flowcharts**: Best for processes and decisions
- **Sequence**: Show interactions over time
- **Class**: Display system architecture
- **Gantt**: Project timelines and schedules
- **Pie**: Show proportions and distributions
- **Mind Map**: Organize hierarchical ideas
- **Timeline**: Chronological events

---

**Try it yourself!** Copy any of these examples and modify them for your needs.

*What's your favorite diagram type? Let me know in the comments!*
`
  },
  {
    id: '09-code-block-examples',
    title: 'Code block examples',
    content: `# Code Block Examples

A showcase of syntax-highlighted code blocks in various programming languages.

## Table of Contents

- [TypeScript](#typescript)
- [JavaScript](#javascript)
- [Python](#python)
- [Bash/Shell](#bashshell)
- [HTML & CSS](#html--css)
- [JSON](#json)
- [SQL](#sql)
- [Terminal Output](#terminal-output)

## TypeScript

TypeScript with full type annotations and modern features.

### Interface and Function

\`\`\`typescript
interface BlogPost {
  id: string;
  title: string;
  content: string;
  publishedAt: Date;
  tags: string[];
  author: {
    name: string;
    email: string;
  };
}

function createBlogPost(
  title: string,
  content: string,
  tags: string[] = []
): BlogPost {
  return {
    id: crypto.randomUUID(),
    title,
    content,
    publishedAt: new Date(),
    tags,
    author: {
      name: 'Naranyala',
      email: 'hello@example.com',
    },
  };
}

// Usage
const post = createBlogPost(
  'My First Post',
  'Hello, World!',
  ['introduction', 'welcome']
);

console.log(\`Created post: \${post.id}\`);
\`\`\`

### Class with Decorators

\`\`\`typescript
@Component({
  selector: 'app-blog',
  template: \`
    <div class="blog-container">
      <h1>{{ title }}</h1>
      <ng-content></ng-content>
    </div>
  \`,
  styles: [\`
    .blog-container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
    }
  \`],
})
export class BlogComponent implements OnInit {
  @Input() title = 'My Blog';
  @Output() postPublished = new EventEmitter<Post>();
  
  private readonly posts: Post[] = [];
  
  constructor(private readonly postService: PostService) {}
  
  async ngOnInit(): Promise<void> {
    const posts = await this.postService.getAll();
    this.posts.push(...posts);
  }
  
  publishPost(post: Post): void {
    this.postService.create(post);
    this.postPublished.emit(post);
  }
}
\`\`\`

### Async/Await Pattern

\`\`\`typescript
async function fetchBlogPosts(
  page: number = 1,
  limit: number = 10
): Promise<PaginatedResult<Post[]>> {
  try {
    const response = await fetch(
      \`/api/posts?page=\${page}&limit=\${limit}\`
    );
    
    if (!response.ok) {
      throw new Error(\`HTTP error! status: \${response.status}\`);
    }
    
    const data = await response.json();
    
    return {
      data: data.posts,
      total: data.total,
      page,
      limit,
      hasMore: page * limit < data.total,
    };
  } catch (error) {
    console.error('Failed to fetch posts:', error);
    throw error;
  }
}

// With retry logic
async function fetchWithRetry(
  url: string,
  retries: number = 3
): Promise<Response> {
  for (let i = 0; i < retries; i++) {
    try {
      const response = await fetch(url);
      if (response.ok) return response;
    } catch (error) {
      if (i === retries - 1) throw error;
      await new Promise(resolve => 
        setTimeout(resolve, 1000 * (i + 1))
      );
    }
  }
  throw new Error('Max retries reached');
}
\`\`\`

## JavaScript

Modern ES6+ JavaScript with async patterns.

### Module Exports

\`\`\`javascript
/**
 * Blog utilities module
 * @module blog/utils
 */

export const formatDate = (date) => {
  return new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }).format(date);
};

export const slugify = (text) => {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .trim();
};

export default {
  formatDate,
  slugify,
  truncate: (text, length = 100) => {
    return text.length > length 
      ? text.slice(0, length) + '...' 
      : text;
  },
};
\`\`\`

### Event Handling

\`\`\`javascript
class BlogReader {
  constructor(container) {
    this.container = container;
    this.scrollProgress = 0;
    this.init();
  }
  
  init() {
    window.addEventListener('scroll', this.handleScroll.bind(this));
    document.querySelectorAll('.code-block').forEach(block => {
      block.addEventListener('copy', this.handleCopy.bind(this));
    });
  }
  
  handleScroll() {
    const scrollTop = window.scrollY;
    const docHeight = document.body.scrollHeight - window.innerHeight;
    this.scrollProgress = (scrollTop / docHeight) * 100;
    this.updateProgressBar();
  }
  
  handleCopy(event) {
    const code = event.target.querySelector('code').textContent;
    navigator.clipboard.writeText(code);
    this.showCopyFeedback();
  }
  
  updateProgressBar() {
    const bar = document.getElementById('progress-bar');
    if (bar) {
      bar.style.width = \`\${this.scrollProgress}%\`;
    }
  }
  
  showCopyFeedback() {
    const toast = document.createElement('div');
    toast.className = 'toast';
    toast.textContent = 'Copied!';
    document.body.appendChild(toast);
    setTimeout(() => toast.remove(), 2000);
  }
}
\`\`\`

## Python

Python 3.x with type hints and modern features.

### Data Processing

\`\`\`python
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import List, Optional

@dataclass
class BlogPost:
    """Represents a blog post"""
    title: str
    content: str
    tags: List[str]
    published_at: Optional[datetime] = None
    draft: bool = True
    
    def publish(self) -> None:
        """Publish the blog post"""
        self.published_at = datetime.now()
        self.draft = False
    
    def word_count(self) -> int:
        """Count words in the post"""
        return len(self.content.split())
    
    def reading_time(self, wpm: int = 200) -> int:
        """Calculate reading time in minutes"""
        return max(1, self.word_count() // wpm)

# Usage
post = BlogPost(
    title="My First Post",
    content="Hello, World! " * 100,
    tags=["introduction", "welcome"]
)

print(f"Reading time: {post.reading_time()} minutes")
post.publish()
print(f"Published at: {post.published_at}")
\`\`\`

### Web Scraping

\`\`\`python
import requests
from bs4 import BeautifulSoup
from typing import Dict, List

def scrape_blog_posts(url: str) -> List[Dict]:
    """Scrape blog posts from a URL"""
    response = requests.get(url)
    response.raise_for_status()
    
    soup = BeautifulSoup(response.text, 'html.parser')
    posts = []
    
    for article in soup.select('.blog-post'):
        post = {
            'title': article.select_one('h2').text.strip(),
            'link': article.select_one('a')['href'],
            'date': article.select_one('.date').text.strip(),
            'tags': [
                tag.text for tag in article.select('.tag')
            ],
        }
        posts.append(post)
    
    return posts

# Batch processing
def process_posts(posts: List[Dict], batch_size: int = 10):
    """Process posts in batches"""
    for i in range(0, len(posts), batch_size):
        batch = posts[i:i + batch_size]
        print(f"Processing batch {i // batch_size + 1}")
        
        for post in batch:
            # Process each post
            yield post

# Usage
posts = scrape_blog_posts('https://example.com/blog')
for post in process_posts(posts):
    print(f"Processed: {post['title']}")
\`\`\`

## Bash/Shell

Shell scripts for automation.

### Deployment Script

\`\`\`bash
#!/bin/bash

# Blog Deployment Script
# Usage: ./deploy.sh [environment]

set -e  # Exit on error

# Configuration
ENVIRONMENT=\${1:-production}
BUILD_DIR="dist"
REMOTE_USER="deploy"
REMOTE_HOST="blog.example.com"
REMOTE_PATH="/var/www/blog"

# Colors for output
RED='\\e[0;31m'
GREEN='\\e[0;32m'
YELLOW='\\e[1;33m'
NC='\\e[0m' # No Color

echo -e "\${GREEN}🚀 Starting deployment to \${ENVIRONMENT}\${NC}"

# Step 1: Build
echo -e "\${YELLOW}Building project...\${NC}"
bun run build

if [ $? -ne 0 ]; then
    echo -e "\${RED}❌ Build failed!\${NC}"
    exit 1
fi

echo -e "\${GREEN}✅ Build successful\${NC}"

# Step 2: Test
echo -e "\${YELLOW}Running tests...\${NC}"
bun test

# Step 3: Deploy
echo -e "\${YELLOW}Deploying to server...\${NC}"
rsync -avz \
    --delete \
    --exclude '.git' \
    \${BUILD_DIR}/ \
    \${REMOTE_USER}@\${REMOTE_HOST}:\${REMOTE_PATH}/

# Step 4: Restart services
echo -e "\${YELLOW}Restarting services...\${NC}"
ssh \${REMOTE_USER}@\${REMOTE_HOST} << 'ENDSSH'
    sudo systemctl restart nginx
    sudo systemctl reload php-fpm
ENDSSH

echo -e "\${GREEN}🎉 Deployment complete!\${NC}"
echo -e "View your site at: https://\${REMOTE_HOST}"
\`\`\`

### Photo Organization

\`\`\`bash
#!/bin/bash

# Organize photos by date
PHOTOS_DIR="$1"

if [ -z "$PHOTOS_DIR" ]; then
    echo "Usage: $0 <photos_directory>"
    exit 1
fi

cd "$PHOTOS_DIR" || exit

# Process each JPG file
for photo in *.JPG *.jpg; do
    [ -f "$photo" ] || continue
    
    # Extract date from filename (assumes YYYYMMDD format)
    DATE=$(echo "$photo" | grep -oE '[0-9]{8}' | head -1)
    
    if [ -n "$DATE" ]; then
        YEAR=\${DATE:0:4}
        MONTH=\${DATE:4:2}
        
        # Create directory structure
        mkdir -p "$YEAR/$MONTH"
        
        # Move photo
        mv "$photo" "$YEAR/$MONTH/"
        echo "Moved: $photo -> $YEAR/$MONTH/"
    else
        echo "Skipping (no date): $photo"
    fi
done

echo "Done!"
\`\`\`

## HTML & CSS

Modern HTML5 and CSS3.

### Semantic HTML

\`\`\`html
<article class="blog-post">
  <header class="post-header">
    <h1 class="post-title">My Amazing Journey</h1>
    <div class="post-meta">
      <time datetime="2026-03-30">March 30, 2026</time>
      <span class="post-author">By Naranyala</span>
    </div>
    <img 
      src="/images/journey-hero.jpg" 
      alt="Beautiful landscape from my journey"
      loading="lazy"
      class="post-hero-image"
    >
  </header>
  
  <div class="post-content">
    <p class="lead">This is the story of my incredible adventure...</p>
    
    <section>
      <h2>The Beginning</h2>
      <p>It all started when...</p>
    </section>
    
    <figure>
      <img src="/images/moment.jpg" alt="A special moment">
      <figcaption>Capturing the perfect moment</figcaption>
    </figure>
  </div>
  
  <footer class="post-footer">
    <div class="post-tags">
      <a href="/tag/travel">travel</a>
      <a href="/tag/adventure">adventure</a>
    </div>
    <div class="post-share">
      <button class="share-twitter">Share on Twitter</button>
      <button class="share-facebook">Share on Facebook</button>
    </div>
  </footer>
</article>
\`\`\`

### CSS Grid Layout

\`\`\`css
.blog-layout {
  display: grid;
  grid-template-columns: 1fr 300px;
  grid-template-areas:
    "header header"
    "main sidebar"
    "footer footer";
  gap: 2rem;
  max-width: 1400px;
  margin: 0 auto;
}

@media (max-width: 1024px) {
  .blog-layout {
    grid-template-columns: 1fr;
    grid-template-areas:
      "header"
      "main"
      "sidebar"
      "footer";
  }
}

.header { grid-area: header; }
.main { grid-area: main; }
.sidebar { grid-area: sidebar; }
.footer { grid-area: footer; }

/* Card hover effects */
.post-card {
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.post-card:hover {
  transform: translateY(-4px);
  box-shadow: 0 12px 24px rgba(0, 0, 0, 0.3);
}
\`\`\`

## JSON

Configuration and data structures.

### Blog Configuration

\`\`\`json
{
  "blog": {
    "title": "Naranyala's Blog",
    "description": "Stories, experiences, and creative projects",
    "url": "https://naranyala.com",
    "language": "en-US",
    "author": {
      "name": "Naranyala",
      "email": "hello@example.com",
      "social": {
        "twitter": "@naranyala",
        "instagram": "@naranyala"
      }
    }
  },
  "seo": {
    "googleAnalytics": "GA-XXXXX",
    "sitemap": true,
    "robotsTxt": true
  },
  "features": {
    "comments": true,
    "newsletter": true,
    "search": true,
    "darkMode": true
  }
}
\`\`\`

### API Response

\`\`\`json
{
  "success": true,
  "data": {
    "posts": [
      {
        "id": "post-123",
        "title": "My Creative Journey",
        "slug": "my-creative-journey",
        "excerpt": "A story about finding creativity...",
        "publishedAt": "2026-03-30T09:00:00Z",
        "tags": ["creativity", "lifestyle"],
        "readingTime": 8,
        "coverImage": "/images/creative-journey.jpg"
      }
    ],
    "pagination": {
      "currentPage": 1,
      "totalPages": 10,
      "totalPosts": 100,
      "hasNext": true,
      "hasPrev": false
    }
  }
}
\`\`\`

## SQL

Database queries.

### Blog Database Schema

\`\`\`sql
-- Create posts table
CREATE TABLE posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    content TEXT NOT NULL,
    excerpt TEXT,
    status VARCHAR(20) DEFAULT 'draft',
    published_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for slug lookups
CREATE INDEX idx_posts_slug ON posts(slug);

-- Create index for published posts
CREATE INDEX idx_posts_published 
ON posts(published_at) 
WHERE status = 'published';

-- Query recent published posts
SELECT 
    p.id,
    p.title,
    p.slug,
    p.excerpt,
    p.published_at,
    COUNT(c.id) as comment_count
FROM posts p
LEFT JOIN comments c ON c.post_id = p.id
WHERE p.status = 'published'
  AND p.published_at <= NOW()
GROUP BY p.id
ORDER BY p.published_at DESC
LIMIT 10;
\`\`\`

## Terminal Output

Console and terminal output examples.

### Build Output

\`\`\`terminal
$ bun run build

> Building...
✓ TypeScript compilation complete (2.3s)
✓ Bundling complete (1.8s)
✓ Optimization complete (0.9s)

Build completed successfully!

Output:
  dist/
  ├── index.html (2.4 kB)
  ├── main.js (842 kB)
  ├── styles.css (156 kB)
  └── assets/
      ├── images/ (24 files)
      └── fonts/ (6 files)

Total size: 1.2 MB
Build time: 5.0s
\`\`\`

### Git Commands

\`\`\`terminal
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   src/app/article-reader.ts
        new file:   docs/mermaid-examples.md

$ git commit -m "Add Mermaid.js examples article"
[main 8f3a2b1] Add Mermaid.js examples article
 2 files changed, 347 insertions(+)
 create mode 100644 docs/mermaid-examples.md

$ git push
Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 8 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (9/9), 1.24 KiB | 1.24 MiB, done.
Total 9 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6)
To github.com:naranyala/blog.git
   3a2b1c4..8f3a2b1  main -> main
\`\`\`

---

## Syntax Highlighting Features

The code blocks support:

✅ **Multiple languages** - TypeScript, JavaScript, Python, Bash, etc.  
✅ **Line numbers** - For easy reference  
✅ **Copy button** - One-click copy  
✅ **Language badge** - Shows the language  
✅ **Custom titles** - Optional file names  
✅ **Terminal theme** - Special styling for terminal output  
✅ **Diff highlighting** - Show code changes  

## How to Use

\`\`\`\`markdown
\`\`\`language
your code here
\`\`\`
\`\`\`\`

Replace \`language\` with: \`typescript\`, \`javascript\`, \`python\`, \`bash\`, \`html\`, \`css\`, \`json\`, \`sql\`, \`terminal\`, etc.

---

**Happy Coding!** 🚀

*Which language do you use most? Let me know in the comments!*
`
  },
  {
    id: '10-technical-demo',
    title: 'Technical demo',
    content: `# Technical Demo: Code & Diagrams

This article demonstrates the full capabilities of code syntax highlighting and Mermaid.js diagram rendering.

## Table of Contents

- [Code Syntax Highlighting](#code-syntax-highlighting)
- [Mermaid.js Diagrams](#mermaidjs-diagrams)
- [Tables with Borders](#tables-with-borders)
- [Mixed Content](#mixed-content)

## Code Syntax Highlighting

### TypeScript Example

Here's a complete Angular component with decorators and type safety:

\`\`\`typescript
import { Component, Input, Output, EventEmitter } from '@angular/core';

interface BlogPost {
  id: string;
  title: string;
  content: string;
  publishedAt: Date;
  tags: string[];
}

@Component({
  selector: 'app-blog-post',
  template: \`
    <article class="post">
      <h1>{{ post.title }}</h1>
      <time>{{ post.publishedAt | date }}</time>
      <div [innerHTML]="post.content"></div>
    </article>
  \`,
  styles: [\`
    .post {
      max-width: 800px;
      margin: 0 auto;
      padding: 2rem;
    }
  \`],
})
export class BlogPostComponent {
  @Input() post!: BlogPost;
  @Output() share = new EventEmitter<void>();
  
  constructor(private readonly analytics: AnalyticsService) {}
  
  async ngOnInit(): Promise<void> {
    await this.analytics.track('post_view', {
      postId: this.post.id,
    });
  }
  
  onShare(): void {
    this.share.emit();
  }
}
\`\`\`

### Python Data Processing

A complete example with dataclasses and type hints:

\`\`\`python
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional, Dict
from pathlib import Path

@dataclass
class BlogAnalytics:
    """Track blog post analytics"""
    post_id: str
    views: int = 0
    shares: int = 0
    comments: int = 0
    metadata: Dict[str, any] = field(default_factory=dict)
    
    def add_view(self) -> None:
        """Increment view count"""
        self.views += 1
        self.metadata['last_view'] = datetime.now()
    
    def get_engagement_rate(self) -> float:
        """Calculate engagement rate"""
        if self.views == 0:
            return 0.0
        return (self.shares + self.comments) / self.views * 100
    
    def to_dict(self) -> Dict:
        """Convert to dictionary"""
        return {
            'post_id': self.post_id,
            'views': self.views,
            'engagement_rate': f"{self.get_engagement_rate():.2f}%",
        }

# Usage example
if __name__ == '__main__':
    analytics = BlogAnalytics(post_id='post-123')
    analytics.add_view()
    print(analytics.to_dict())
\`\`\`

### Bash Automation Script

Complete deployment script with error handling:

\`\`\`bash
#!/bin/bash

# Blog Deployment Script
# Usage: ./deploy.sh [environment]

set -e  # Exit on error

# Configuration
ENVIRONMENT=\${1:-production}
BUILD_DIR="dist"
REMOTE_USER="deploy"
REMOTE_HOST="blog.example.com"
REMOTE_PATH="/var/www/blog"

# Colors
RED='\\e[0;31m'
GREEN='\\e[0;32m'
YELLOW='\\e[1;33m'
BLUE='\\e[0;34m'
NC='\\e[0m'

log_info() {
    echo -e "\${BLUE}ℹ️  $1\${NC}"
}

log_success() {
    echo -e "\${GREEN}✅ $1\${NC}"
}

log_error() {
    echo -e "\${RED}❌ $1\${NC}"
}

log_warning() {
    echo -e "\${YELLOW}⚠️  $1\${NC}"
}

# Main deployment function
deploy() {
    log_info "Starting deployment to \${ENVIRONMENT}"
    
    # Step 1: Build
    log_info "Building project..."
    if bun run build; then
        log_success "Build completed"
    else
        log_error "Build failed!"
        exit 1
    fi
    
    # Step 2: Test
    log_info "Running tests..."
    if bun test; then
        log_success "All tests passed"
    else
        log_warning "Some tests failed"
        read -p "Continue anyway? (y/n) " -n 1 -r
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi
    
    # Step 3: Deploy
    log_info "Deploying to server..."
    rsync -avz \
        --delete \
        --exclude '.git' \
        \${BUILD_DIR}/ \
        \${REMOTE_USER}@\${REMOTE_HOST}:\${REMOTE_PATH}/
    
    log_success "Deployment complete!"
    log_info "View your site at: https://\${REMOTE_HOST}"
}

# Run deployment
deploy
\`\`\`

### JavaScript Class with Async Operations

Modern ES6+ with async/await and error handling:

\`\`\`javascript
/**
 * Blog API Client
 * Handles all API communication for the blog
 */
class BlogApiClient {
  constructor(baseUrl, apiKey) {
    this.baseUrl = baseUrl;
    this.apiKey = apiKey;
    this.cache = new Map();
  }

  async request(endpoint, options = {}) {
    const url = \`\${this.baseUrl}\${endpoint}\`;
    const cacheKey = \`\${endpoint}:\${JSON.stringify(options)}\`;

    // Check cache first
    if (this.cache.has(cacheKey)) {
      console.log('📦 Returning cached response');
      return this.cache.get(cacheKey);
    }

    try {
      const response = await fetch(url, {
        ...options,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': \`Bearer \${this.apiKey}\`,
          ...options.headers,
        },
      });

      if (!response.ok) {
        throw new Error(\`HTTP \${response.status}: \${response.statusText}\`);
      }

      const data = await response.json();
      
      // Cache the response
      this.cache.set(cacheKey, data);
      
      return data;
    } catch (error) {
      console.error('API request failed:', error);
      throw error;
    }
  }

  async getPosts(page = 1, limit = 10) {
    return this.request(\`/posts?page=\${page}&limit=\${limit}\`);
  }

  async getPost(slug) {
    return this.request(\`/posts/\${slug}\`);
  }

  async createPost(postData) {
    return this.request('/posts', {
      method: 'POST',
      body: JSON.stringify(postData),
    });
  }

  clearCache() {
    this.cache.clear();
    console.log('Cache cleared');
  }
}

// Usage
const api = new BlogApiClient('https://api.example.com', 'your-api-key');
const posts = await api.getPosts(1, 20);
console.log(\`Loaded \${posts.length} posts\`);
\`\`\`

## Mermaid.js Diagrams

### Flowchart: Content Creation Process

This shows my complete content creation workflow:

\`\`\`mermaid
flowchart TD
    A[💡 Inspiration] --> B{Worth Pursuing?}
    B -->|No| C[🗑️ Discard]
    B -->|Yes| D[📝 Planning]
    D --> E[✍️ Content Creation]
    E --> F{Content Type?}
    F -->|Blog Post| G[Writing + Photos]
    F -->|Video| H[Recording + Editing]
    F -->|Photo Essay| I[Photo Selection]
    G --> J[👀 Review]
    H --> J
    I --> J
    J --> K{Ready?}
    K -->|No| E
    K -->|Yes| L[🚀 Publish]
    L --> M[📱 Share on Social]
    M --> N[💬 Engage with Audience]
    N --> O[📊 Analyze Performance]
    O --> P[📈 Learn & Improve]
    P --> A
\`\`\`

### Sequence Diagram: Blog Publishing Flow

Shows the technical flow from draft to published:

\`\`\`mermaid
sequenceDiagram
    autonumber
    participant Author
    participant CMS as Content Management
    participant Build as Build System
    participant Server as Web Server
    participant CDN as CDN
    participant User

    Author->>CMS: Create Draft
    CMS-->>Author: Draft Saved ✓
    
    Author->>CMS: Submit for Review
    CMS->>Build: Trigger Build
    Build->>Build: Install Dependencies
    Build->>Build: Compile TypeScript
    Build->>Build: Bundle Assets
    Build->>Build: Optimize Images
    Build-->>CMS: Build Success ✓
    
    CMS->>Server: Deploy Files
    Server->>CDN: Invalidate Cache
    CDN-->>Server: Cache Cleared ✓
    Server-->>CMS: Deployment Complete ✓
    CMS-->>Author: Published! 🎉
    
    User->>CDN: Request Page
    CDN-->>User: Serve Content ⚡
\`\`\`

### Class Diagram: Blog System Architecture

Shows the database schema and relationships:

\`\`\`mermaid
classDiagram
    class BlogPost {
        +string id
        +string title
        +string slug
        +string content
        +DateTime publishedAt
        +string status
        +publish()
        +update()
        +delete()
    }
    
    class Author {
        +string id
        +string name
        +string email
        +string bio
        +getPosts()
        +writePost()
    }
    
    class Category {
        +string id
        +string name
        +string slug
        +getPosts()
    }
    
    class Tag {
        +string id
        +string name
        +string slug
    }
    
    class Comment {
        +string id
        +string content
        +DateTime createdAt
        +bool approved
        +approve()
        +delete()
    }
    
    class Analytics {
        +string postId
        +int views
        +int shares
        +trackView()
        +getStats()
    }
    
    Author "1" --> "*" BlogPost : writes
    BlogPost "*" --> "*" Category : categorized
    BlogPost "*" --> "*" Tag : tagged
    BlogPost "1" --> "*" Comment : has
    BlogPost "1" --> "1" Analytics : tracked
\`\`\`

### State Diagram: Article Lifecycle

Shows all possible states of a blog post:

\`\`\`mermaid
stateDiagram-v2
    [*] --> Draft : Create
    Draft --> Review : Submit
    Draft --> [*] : Delete
    
    Review --> Draft : Request Changes
    Review --> Approved : Approve
    Review --> Rejected : Reject
    
    Approved --> Scheduled : Schedule
    Approved --> Published : Publish Immediately
    
    Scheduled --> Published : Publish Time Reached
    Scheduled --> Draft : Cancel Schedule
    
    Published --> Updated : Edit
    Updated --> Published : Save Changes
    Published --> Archived : Archive
    
    Archived --> Published : Restore
    Archived --> [*] : Permanent Delete
    
    Rejected --> Draft : Revise
    Rejected --> [*] : Discard
\`\`\`

### Gantt Chart: Content Calendar

Project timeline for monthly content:

\`\`\`mermaid
gantt
    title Blog Content Calendar - April 2026
    dateFormat  YYYY-MM-DD
    axisFormat  %b %d
    
    section Week 1 (Apr 1-7)
    Research Topics       :a1, 2026-04-01, 2d
    Write First Draft     :a2, after a1, 3d
    Add Images            :a3, after a2, 2d
    
    section Week 2 (Apr 8-14)
    Edit Content          :b1, 2026-04-08, 2d
    SEO Optimization      :b2, after b1, 1d
    Publish Post          :b3, after b2, 1d
    
    section Week 3 (Apr 15-21)
    Social Media Campaign :c1, 2026-04-15, 3d
    Engage Comments       :c2, after c1, 4d
    
    section Week 4 (Apr 22-30)
    Analytics Review      :d1, 2026-04-22, 2d
    Plan May Content      :d2, after d1, 3d
    Buffer Days           :d3, after d2, 2d
\`\`\`

### Pie Chart: Content Distribution

Shows the breakdown of content types:

\`\`\`mermaid
pie title Blog Content by Category
    "Travel Stories" : 25
    "Lifestyle" : 30
    "Creative Projects" : 20
    "Personal Growth" : 15
    "Technical Tutorials" : 10
\`\`\`

### Mind Map: Content Strategy

Hierarchical organization of content strategy:

\`\`\`mermaid
mindmap
  root((Content Strategy))
    Planning
      Research
        Trend Analysis
        Keyword Research
      Calendar
        Monthly Plan
        Weekly Schedule
    Creation
      Writing
        First Draft
        Editing
      Visuals
        Photography
        Graphics
    Distribution
      Blog
      Social Media
        Instagram
        Twitter
        LinkedIn
      Newsletter
        Weekly Digest
    Engagement
      Comments
      Email Replies
      Social Interactions
    Analytics
      Page Views
      Engagement Rate
      Conversion
\`\`\`

## Tables with Borders

### Content Categories Table

Full table with all borders visible:

| Category | Posts | Avg Read Time | Engagement Rate | Last Updated |
|----------|-------|---------------|-----------------|--------------|
| Travel | 25 | 8 min | 4.2% | 2026-03-28 |
| Lifestyle | 30 | 6 min | 5.1% | 2026-03-29 |
| Creative | 20 | 10 min | 3.8% | 2026-03-27 |
| Growth | 15 | 7 min | 4.5% | 2026-03-30 |
| Technical | 10 | 12 min | 6.2% | 2026-03-26 |

### Technology Stack Table

Another example with different content:

| Technology | Purpose | Version | Status |
|------------|---------|---------|--------|
| Angular | Frontend Framework | 19.x | ✅ Active |
| Rspack | Build Tool | 1.x | ✅ Active |
| Bun | Runtime & Package Manager | 1.x | ✅ Active |
| TypeScript | Language | 5.x | ✅ Active |
| Marked | Markdown Parser | 17.x | ✅ Active |
| Mermaid | Diagram Library | 11.x | ✅ Active |

### Social Media Platforms Table

Table showing platform statistics:

| Platform | Followers | Posts | Engagement | Priority |
|----------|-----------|-------|------------|----------|
| Instagram | 15.2K | 342 | 4.8% | 🔴 High |
| Twitter | 8.5K | 1,247 | 3.2% | 🟡 Medium |
| LinkedIn | 5.1K | 89 | 5.6% | 🟢 Low |
| YouTube | 2.3K | 45 | 7.1% | 🟡 Medium |

## Mixed Content

### Code + Diagram Combination

Here's how I process photos, shown in both code and diagram:

\`\`\`python
from PIL import Image
from pathlib import Path

def process_photo(input_path: str, output_path: str) -> dict:
    """Process a photo with standard adjustments"""
    img = Image.open(input_path)
    
    # Basic adjustments
    img = img.adjust_brightness(1.2)
    img = img.adjust_contrast(1.1)
    img = img.adjust_saturation(1.3)
    
    # Resize for web
    img.thumbnail((1920, 1080))
    
    # Save with optimization
    img.save(output_path, optimize=True, quality=85)
    
    return {
        'original_size': img.size,
        'output_path': output_path,
        'format': img.format,
    }
\`\`\`

The workflow visualized:

\`\`\`mermaid
flowchart LR
    A[📸 Raw Photo] --> B[💡 Adjustments]
    B --> C[📐 Resize]
    C --> D[💾 Export]
    D --> E[🌐 Upload]
    E --> F[📤 Publish]
\`\`\`

---

## Summary

This article demonstrates:

✅ **Syntax Highlighting** - TypeScript, Python, Bash, JavaScript  
✅ **Mermaid Diagrams** - 8 different diagram types  
✅ **Tables with Borders** - Full border styling on all cells  
✅ **Mixed Content** - Code and diagrams together  
✅ **Responsive Design** - Works on mobile and desktop  

---

**Questions?** Drop them in the comments below! 👇
`
  }
];

export const ARTICLE_IDS = ARTICLES_BUNDLE.map(a => a.id);

export function getBundledArticle(id: string): Article | undefined {
  return ARTICLES_BUNDLE.find(article => article.id === id);
}

export function getAllBundledArticles(): Article[] {
  return ARTICLES_BUNDLE;
}
