import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';

/**
 * Script to bundle markdown articles into a TypeScript module
 * This allows articles to be embedded in the JavaScript bundle for static site deployment
 */

const DOCS_DIR = join(__dirname, '..', 'docs');
const OUTPUT_DIR = join(__dirname, '..', 'src', 'app', 'shared');
const OUTPUT_FILE = join(OUTPUT_DIR, 'articles.bundle.ts');

// Articles to include in the bundle
const ARTICLES_TO_INCLUDE = [
  '01-welcome.md',
  '02-cape-town-adventure.md',
  '03-finding-balance-wellness.md',
  '04-art-of-slow-living.md',
  '05-creative-confidence.md',
  '06-photography-journey.md',
  'README.md',
];

interface Article {
  id: string;
  title: string;
  content: string;
}

function slugify(filename: string): string {
  return filename.replace('.md', '').toLowerCase();
}

function formatTitle(filename: string): string {
  const title = filename
    .replace('.md', '')
    .replace(/^\d+-/, '')
    .replace(/-/g, ' ');
  return title.charAt(0).toUpperCase() + title.slice(1);
}

function escapeTemplateLiteral(content: string): string {
  // Escape backticks and ${ to prevent template literal injection
  return content.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function generateArticlesBundle(): void {
  console.log('[Generate Articles] Starting...');
  console.log(`[Generate Articles] Reading from: ${DOCS_DIR}`);
  console.log(`[Generate Articles] Writing to: ${OUTPUT_FILE}`);

  // Ensure output directory exists
  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
    console.log(`[Generate Articles] Created directory: ${OUTPUT_DIR}`);
  }

  const articles: Article[] = [];
  const errors: string[] = [];

  for (const filename of ARTICLES_TO_INCLUDE) {
    const filePath = join(DOCS_DIR, filename);

    if (!existsSync(filePath)) {
      errors.push(`File not found: ${filePath}`);
      console.warn(`[Generate Articles] Warning: ${filePath} not found, skipping...`);
      continue;
    }

    try {
      const content = readFileSync(filePath, 'utf-8');
      const id = slugify(filename);
      const title = formatTitle(filename);

      articles.push({ id, title, content });
      console.log(`[Generate Articles] ✓ Loaded: ${filename} (${content.length} chars)`);
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      errors.push(`Error reading ${filename}: ${errorMsg}`);
      console.error(`[Generate Articles] Error reading ${filename}:`, errorMsg);
    }
  }

  if (articles.length === 0) {
    console.error('[Generate Articles] No articles found! Aborting...');
    process.exit(1);
  }

  // Generate TypeScript module
  const moduleContent = generateModuleContent(articles);

  // Write the bundle file
  writeFileSync(OUTPUT_FILE, moduleContent, 'utf-8');
  console.log(`[Generate Articles] ✓ Generated bundle: ${OUTPUT_FILE}`);
  console.log(`[Generate Articles] Total articles: ${articles.length}`);
  console.log(`[Generate Articles] Total size: ${moduleContent.length} chars`);

  if (errors.length > 0) {
    console.log(`[Generate Articles] Warnings: ${errors.length}`);
    errors.forEach((err) => console.log(`  - ${err}`));
  }

  console.log('[Generate Articles] Done!');
}

function generateModuleContent(articles: Article[]): string {
  const timestamp = new Date().toISOString();

  // Generate article data as const for better type safety
  const articlesData = articles
    .map((article) => {
      const escapedContent = escapeTemplateLiteral(article.content);
      return `  {
    id: '${article.id}',
    title: '${article.title.replace(/'/g, "\\'")}',
    content: \`${escapedContent}\`
  }`;
    })
    .join(',\n');

  return `/**
 * Auto-generated articles bundle
 * Generated at: ${timestamp}
 *
 * This file contains all markdown articles bundled into the JavaScript.
 * DO NOT edit this file manually - it will be regenerated on build.
 *
 * To modify articles, edit the .md files in the /docs folder.
 */

import type { Article } from '../services/article.service';

export const ARTICLES_BUNDLE: Article[] = [
${articlesData}
];

export const ARTICLE_IDS = ARTICLES_BUNDLE.map(a => a.id);

export function getBundledArticle(id: string): Article | undefined {
  return ARTICLES_BUNDLE.find(article => article.id === id);
}

export function getAllBundledArticles(): Article[] {
  return ARTICLES_BUNDLE;
}
`;
}

// Run the script
generateArticlesBundle();
