pub struct DocEntry {
    pub path: &'static str,
    pub title: &'static str,
    pub content: &'static str,
}

pub const DOCS: &[DocEntry] = &[
    DocEntry { path: "00-introduction/00-overview", title: "Overview of Tauri and Leptos", content: include_str!("../docs/00-introduction/00-overview.md") },
    DocEntry { path: "00-introduction/01-why-this-stack", title: "Why Choose This Stack?", content: include_str!("../docs/00-introduction/01-why-this-stack.md") },
    DocEntry { path: "00-introduction/02-architecture", title: "Architecture Overview", content: include_str!("../docs/00-introduction/02-architecture.md") },
    DocEntry { path: "01-leptos-frontend/00-getting-started", title: "Getting Started with Leptos in Tauri", content: include_str!("../docs/01-leptos-frontend/00-getting-started.md") },
    DocEntry { path: "01-leptos-frontend/01-reactive-state", title: "Reactive State in Leptos", content: include_str!("../docs/01-leptos-frontend/01-reactive-state.md") },
    DocEntry { path: "01-leptos-frontend/02-component-structure", title: "Component Structure", content: include_str!("../docs/01-leptos-frontend/02-component-structure.md") },
    DocEntry { path: "02-tauri-backend/00-backend-overview", title: "The Tauri Backend Overview", content: include_str!("../docs/02-tauri-backend/00-backend-overview.md") },
    DocEntry { path: "02-tauri-backend/01-tauri-commands", title: "Tauri Commands", content: include_str!("../docs/02-tauri-backend/01-tauri-commands.md") },
    DocEntry { path: "02-tauri-backend/02-state-management", title: "Backend State Management", content: include_str!("../docs/02-tauri-backend/02-state-management.md") },
    DocEntry { path: "02-tauri-backend/03-security-and-permissions", title: "Security and Permissions", content: include_str!("../docs/02-tauri-backend/03-security-and-permissions.md") },
    DocEntry { path: "03-bridge-communication/00-ipc-basics", title: "IPC Basics: The Bridge", content: include_str!("../docs/03-bridge-communication/00-ipc-basics.md") },
    DocEntry { path: "03-bridge-communication/01-invoking-commands", title: "Invoking Commands from Leptos", content: include_str!("../docs/03-bridge-communication/01-invoking-commands.md") },
    DocEntry { path: "03-bridge-communication/02-event-system", title: "The Event System", content: include_str!("../docs/03-bridge-communication/02-event-system.md") },
    DocEntry { path: "03-bridge-communication/03-type-safe-sharing", title: "Type-Safe Sharing", content: include_str!("../docs/03-bridge-communication/03-type-safe-sharing.md") },
    DocEntry { path: "04-desktop-integration/00-os-api-overview", title: "OS API Overview", content: include_str!("../docs/04-desktop-integration/00-os-api-overview.md") },
    DocEntry { path: "04-desktop-integration/01-filesystem-access", title: "Filesystem Access", content: include_str!("../docs/04-desktop-integration/01-filesystem-access.md") },
    DocEntry { path: "04-desktop-integration/02-system-tray-menus", title: "System Tray and Menus", content: include_str!("../docs/04-desktop-integration/02-system-tray-menus.md") },
    DocEntry { path: "04-desktop-integration/03-window-management", title: "Window Management", content: include_str!("../docs/04-desktop-integration/03-window-management.md") },
    DocEntry { path: "04-desktop-integration/04-notifications", title: "Native Notifications", content: include_str!("../docs/04-desktop-integration/04-notifications.md") },
    DocEntry { path: "05-build-and-distribute/00-build-process", title: "The Build Process", content: include_str!("../docs/05-build-and-distribute/00-build-process.md") },
    DocEntry { path: "05-build-and-distribute/01-target-platforms", title: "Target Platforms", content: include_str!("../docs/05-build-and-distribute/01-target-platforms.md") },
    DocEntry { path: "05-build-and-distribute/02-optimization-tips", title: "Optimization Tips", content: include_str!("../docs/05-build-and-distribute/02-optimization-tips.md") },
];
